from enum import Enum

class RiskLevel(Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"

class RecommendationType(Enum):
    CONTACT_DRIVER = "CONTACT_DRIVER"
    REVIEW_DELIVERY_WINDOW = "REVIEW_DELIVERY_WINDOW"
    CHECK_THERMAL_INTEGRITY = "CHECK_THERMAL_INTEGRITY"
    ESCALATE_INCIDENT = "ESCALATE_INCIDENT"
    MONITOR_OPERATION = "MONITOR_OPERATION"
    CHECK_TRACKING = "CHECK_TRACKING"
    ASSIGN_DRIVER = "ASSIGN_DRIVER"
    ASSIGN_VEHICLE = "ASSIGN_VEHICLE"
    PRIORITIZE_OPERATION = "PRIORITIZE_OPERATION"
