from django.urls import path

from .document_views import (
    DocumentDetailView,
    DocumentDownloadView,
    DocumentListView,
    DocumentReviewListView,
    DocumentUploadView,
)
from .driver_route_intent_views import (
    DriverRouteIntentActivateView,
    DriverRouteIntentCancelView,
    DriverRouteIntentCreateView,
    DriverRouteIntentDetailView,
    DriverRouteIntentListView,
    DriverRouteIntentUpdateView,
)
from .freight_offer_views import (
    FreightOfferAddTargetView,
    FreightOfferCancelSelectionView,
    FreightOfferCancelView,
    FreightOfferConfirmSelectionView,
    FreightOfferCreateView,
    FreightOfferDeclineSelectionView,
    FreightOfferDetailView,
    FreightOfferListView,
    FreightOfferMatchingGenerateView,
    FreightOfferMatchingInviteView,
    FreightOfferMatchingRegenerateView,
    FreightOfferPauseView,
    FreightOfferPublishView,
    FreightOfferReadyView,
    FreightOfferRemoveTargetView,
    FreightOfferResumeView,
    FreightOfferSelectCandidateView,
    FreightOfferSimulateInterestView,
    FreightOfferUpdateView,
    FreightOfferWithdrawInterestView,
)
from .freight_quote_views import (
    FreightQuoteApproveView,
    FreightQuoteCancelView,
    FreightQuoteCreateView,
    FreightQuoteDetailView,
    FreightQuoteListView,
    FreightQuoteRejectView,
    FreightQuoteReviewView,
    FreightQuoteReviseView,
    FreightQuoteSendView,
    FreightQuoteUpdateView,
)
from .freight_request_views import (
    FreightRequestAssignOwnerView,
    FreightRequestCancelView,
    FreightRequestCreateView,
    FreightRequestDetailView,
    FreightRequestListView,
    FreightRequestStatusChangeView,
    FreightRequestSubmitView,
    FreightRequestUpdateView,
)
from .views import (
    AuditLogDetailView,
    AuditLogListView,
    BackofficeDashboardView,
    BackofficeLoginView,
    BackofficeLogoutView,
    BranchCreateView,
    BranchListView,
    BranchUpdateView,
    BusinessUnitCreateView,
    BusinessUnitListView,
    BusinessUnitUpdateView,
    CarrierCreateView,
    CarrierDetailView,
    CarrierListView,
    CarrierStatusChangeView,
    CarrierUpdateView,
    CustomerCreateView,
    CustomerDetailView,
    CustomerListView,
    CustomerStatusChangeView,
    CustomerUpdateView,
    DashboardAnalyticsView,
    DashboardCommercialView,
    DashboardComplianceView,
    DashboardFinanceView,
    DashboardFleetHealthView,
    DashboardMarketplaceView,
    DashboardOperationsView,
    DashboardRelationshipView,
    DepartmentCreateView,
    DepartmentListView,
    DepartmentUpdateView,
    DriverCreateView,
    DriverDetailView,
    DriverListView,
    DriverStatusChangeView,
    DriverUpdateView,
    MembershipCreateView,
    MembershipDetailView,
    MembershipListView,
    MembershipUpdateView,
    OrganizationCreateView,
    OrganizationDetailView,
    OrganizationListView,
    OrganizationUpdateView,
    PermissionListView,
    RoleDetailView,
    RoleListView,
    TeamCreateView,
    TeamListView,
    TeamUpdateView,
    UserCreateView,
    UserDetailView,
    UserListView,
    UserStatusChangeView,
    UserUpdateView,
    VehicleCreateView,
    VehicleDetailView,
    VehicleListView,
    VehicleStatusChangeView,
    VehicleUpdateView,
)

app_name = "backoffice"

urlpatterns = [
    path("", BackofficeDashboardView.as_view(), name="dashboard"),
    path("dashboard/operations/", DashboardOperationsView.as_view(), name="dashboard_operations"),
    path(
        "dashboard/relationship/",
        DashboardRelationshipView.as_view(),
        name="dashboard_relationship",
    ),
    path("dashboard/finance/", DashboardFinanceView.as_view(), name="dashboard_finance"),
    path("dashboard/analytics/", DashboardAnalyticsView.as_view(), name="dashboard_analytics"),
    path(
        "dashboard/commercial/",
        DashboardCommercialView.as_view(),
        name="dashboard_commercial",
    ),
    path(
        "dashboard/marketplace/",
        DashboardMarketplaceView.as_view(),
        name="dashboard_marketplace",
    ),
    path(
        "dashboard/compliance/",
        DashboardComplianceView.as_view(),
        name="dashboard_compliance",
    ),
    path(
        "dashboard/fleet-health/",
        DashboardFleetHealthView.as_view(),
        name="dashboard_fleet_health",
    ),
    path("login/", BackofficeLoginView.as_view(), name="login"),
    path("logout/", BackofficeLogoutView.as_view(), name="logout"),
    path("organizations/", OrganizationListView.as_view(), name="organizations"),
    path("organizations/new/", OrganizationCreateView.as_view(), name="organization_create"),
    path("organizations/<uuid:pk>/", OrganizationDetailView.as_view(), name="organization_detail"),
    path(
        "organizations/<uuid:pk>/edit/", OrganizationUpdateView.as_view(), name="organization_edit"
    ),
    path("business-units/", BusinessUnitListView.as_view(), name="business_units"),
    path("business-units/new/", BusinessUnitCreateView.as_view(), name="business_unit_create"),
    path(
        "business-units/<uuid:pk>/edit/",
        BusinessUnitUpdateView.as_view(),
        name="business_unit_edit",
    ),
    path("branches/", BranchListView.as_view(), name="branches"),
    path("branches/new/", BranchCreateView.as_view(), name="branch_create"),
    path("branches/<uuid:pk>/edit/", BranchUpdateView.as_view(), name="branch_edit"),
    path("departments/", DepartmentListView.as_view(), name="departments"),
    path("departments/new/", DepartmentCreateView.as_view(), name="department_create"),
    path("departments/<uuid:pk>/edit/", DepartmentUpdateView.as_view(), name="department_edit"),
    path("teams/", TeamListView.as_view(), name="teams"),
    path("teams/new/", TeamCreateView.as_view(), name="team_create"),
    path("teams/<uuid:pk>/edit/", TeamUpdateView.as_view(), name="team_edit"),
    path("drivers/", DriverListView.as_view(), name="drivers"),
    path("drivers/new/", DriverCreateView.as_view(), name="driver_create"),
    path("drivers/<uuid:pk>/", DriverDetailView.as_view(), name="driver_detail"),
    path("drivers/<uuid:pk>/edit/", DriverUpdateView.as_view(), name="driver_edit"),
    path("drivers/<uuid:pk>/status/", DriverStatusChangeView.as_view(), name="driver_status"),
    path("vehicles/", VehicleListView.as_view(), name="vehicles"),
    path("vehicles/new/", VehicleCreateView.as_view(), name="vehicle_create"),
    path("vehicles/<uuid:pk>/", VehicleDetailView.as_view(), name="vehicle_detail"),
    path("vehicles/<uuid:pk>/edit/", VehicleUpdateView.as_view(), name="vehicle_edit"),
    path("vehicles/<uuid:pk>/status/", VehicleStatusChangeView.as_view(), name="vehicle_status"),
    path("customers/", CustomerListView.as_view(), name="customers"),
    path("customers/new/", CustomerCreateView.as_view(), name="customer_create"),
    path("customers/<uuid:pk>/", CustomerDetailView.as_view(), name="customer_detail"),
    path("customers/<uuid:pk>/edit/", CustomerUpdateView.as_view(), name="customer_edit"),
    path("customers/<uuid:pk>/status/", CustomerStatusChangeView.as_view(), name="customer_status"),
    path("carriers/", CarrierListView.as_view(), name="carriers"),
    path("carriers/new/", CarrierCreateView.as_view(), name="carrier_create"),
    path("carriers/<uuid:pk>/", CarrierDetailView.as_view(), name="carrier_detail"),
    path("carriers/<uuid:pk>/edit/", CarrierUpdateView.as_view(), name="carrier_edit"),
    path("carriers/<uuid:pk>/status/", CarrierStatusChangeView.as_view(), name="carrier_status"),
    path("users/", UserListView.as_view(), name="users"),
    path("users/new/", UserCreateView.as_view(), name="user_create"),
    path("users/<uuid:pk>/", UserDetailView.as_view(), name="user_detail"),
    path("users/<uuid:pk>/edit/", UserUpdateView.as_view(), name="user_edit"),
    path("users/<uuid:pk>/status/", UserStatusChangeView.as_view(), name="user_status"),
    path("memberships/", MembershipListView.as_view(), name="memberships"),
    path("memberships/new/", MembershipCreateView.as_view(), name="membership_create"),
    path("memberships/<uuid:pk>/", MembershipDetailView.as_view(), name="membership_detail"),
    path("memberships/<uuid:pk>/edit/", MembershipUpdateView.as_view(), name="membership_edit"),
    path("roles/", RoleListView.as_view(), name="roles"),
    path("roles/<uuid:pk>/", RoleDetailView.as_view(), name="role_detail"),
    path("permissions/", PermissionListView.as_view(), name="permissions"),
    path("audit/", AuditLogListView.as_view(), name="audit"),
    path("audit/<uuid:pk>/", AuditLogDetailView.as_view(), name="audit_detail"),
    path("documents/", DocumentListView.as_view(), name="documents"),
    path("documents/review/", DocumentReviewListView.as_view(), name="documents_review"),
    path("documents/upload/", DocumentUploadView.as_view(), name="document_upload"),
    path("documents/<uuid:pk>/", DocumentDetailView.as_view(), name="document_detail"),
    path("documents/<uuid:pk>/download/", DocumentDownloadView.as_view(), name="document_download"),
    path("freight-requests/", FreightRequestListView.as_view(), name="freight_requests"),
    path(
        "freight-requests/new/",
        FreightRequestCreateView.as_view(),
        name="freight_request_create",
    ),
    path(
        "freight-requests/<uuid:pk>/",
        FreightRequestDetailView.as_view(),
        name="freight_request_detail",
    ),
    path(
        "freight-requests/<uuid:pk>/edit/",
        FreightRequestUpdateView.as_view(),
        name="freight_request_edit",
    ),
    path(
        "freight-requests/<uuid:pk>/submit/",
        FreightRequestSubmitView.as_view(),
        name="freight_request_submit",
    ),
    path(
        "freight-requests/<uuid:pk>/cancel/",
        FreightRequestCancelView.as_view(),
        name="freight_request_cancel",
    ),
    path(
        "freight-requests/<uuid:pk>/status/",
        FreightRequestStatusChangeView.as_view(),
        name="freight_request_status",
    ),
    path(
        "freight-requests/<uuid:pk>/assign-owner/",
        FreightRequestAssignOwnerView.as_view(),
        name="freight_request_assign_owner",
    ),
    path(
        "freight-requests/<uuid:request_pk>/quotes/new/",
        FreightQuoteCreateView.as_view(),
        name="freight_quote_create",
    ),
    path("freight-quotes/", FreightQuoteListView.as_view(), name="freight_quotes"),
    path(
        "freight-quotes/<uuid:pk>/",
        FreightQuoteDetailView.as_view(),
        name="freight_quote_detail",
    ),
    path(
        "freight-quotes/<uuid:pk>/edit/",
        FreightQuoteUpdateView.as_view(),
        name="freight_quote_edit",
    ),
    path(
        "freight-quotes/<uuid:pk>/review/",
        FreightQuoteReviewView.as_view(),
        name="freight_quote_review",
    ),
    path(
        "freight-quotes/<uuid:pk>/approve/",
        FreightQuoteApproveView.as_view(),
        name="freight_quote_approve",
    ),
    path(
        "freight-quotes/<uuid:pk>/reject/",
        FreightQuoteRejectView.as_view(),
        name="freight_quote_reject",
    ),
    path(
        "freight-quotes/<uuid:pk>/send/",
        FreightQuoteSendView.as_view(),
        name="freight_quote_send",
    ),
    path(
        "freight-quotes/<uuid:pk>/cancel/",
        FreightQuoteCancelView.as_view(),
        name="freight_quote_cancel",
    ),
    path(
        "freight-quotes/<uuid:pk>/revise/",
        FreightQuoteReviseView.as_view(),
        name="freight_quote_revise",
    ),
    path("freight-offers/", FreightOfferListView.as_view(), name="freight_offers"),
    path(
        "freight-offers/<uuid:pk>/",
        FreightOfferDetailView.as_view(),
        name="freight_offer_detail",
    ),
    path(
        "freight-offers/<uuid:pk>/edit/",
        FreightOfferUpdateView.as_view(),
        name="freight_offer_edit",
    ),
    path(
        "freight-offers/<uuid:pk>/ready/",
        FreightOfferReadyView.as_view(),
        name="freight_offer_ready",
    ),
    path(
        "freight-offers/<uuid:pk>/publish/",
        FreightOfferPublishView.as_view(),
        name="freight_offer_publish",
    ),
    path(
        "freight-offers/<uuid:pk>/pause/",
        FreightOfferPauseView.as_view(),
        name="freight_offer_pause",
    ),
    path(
        "freight-offers/<uuid:pk>/resume/",
        FreightOfferResumeView.as_view(),
        name="freight_offer_resume",
    ),
    path(
        "freight-offers/<uuid:pk>/cancel/",
        FreightOfferCancelView.as_view(),
        name="freight_offer_cancel",
    ),
    path(
        "freight-offers/<uuid:pk>/targets/add/",
        FreightOfferAddTargetView.as_view(),
        name="freight_offer_target_add",
    ),
    path(
        "freight-offers/<uuid:pk>/targets/<uuid:target_pk>/remove/",
        FreightOfferRemoveTargetView.as_view(),
        name="freight_offer_target_remove",
    ),
    path(
        "freight-requests/<uuid:request_pk>/offers/new/",
        FreightOfferCreateView.as_view(),
        name="freight_offer_create",
    ),
    path(
        "freight-offers/<uuid:pk>/matching/generate/",
        FreightOfferMatchingGenerateView.as_view(),
        name="freight_offer_matching_generate",
    ),
    path(
        "freight-offers/<uuid:pk>/matching/regenerate/",
        FreightOfferMatchingRegenerateView.as_view(),
        name="freight_offer_matching_regenerate",
    ),
    path(
        "freight-offers/<uuid:pk>/matching/candidates/<uuid:candidate_pk>/invite/",
        FreightOfferMatchingInviteView.as_view(),
        name="freight_offer_matching_invite",
    ),
    path(
        "freight-offers/<uuid:pk>/interest/simulate/",
        FreightOfferSimulateInterestView.as_view(),
        name="freight_offer_interest_simulate",
    ),
    path(
        "freight-offers/interests/<uuid:interest_pk>/withdraw/",
        FreightOfferWithdrawInterestView.as_view(),
        name="freight_offer_interest_withdraw",
    ),
    path(
        "freight-offers/interests/<uuid:interest_pk>/select/",
        FreightOfferSelectCandidateView.as_view(),
        name="freight_offer_interest_select",
    ),
    path(
        "freight-offers/selections/<uuid:selection_pk>/cancel/",
        FreightOfferCancelSelectionView.as_view(),
        name="freight_offer_selection_cancel",
    ),
    path(
        "freight-offers/selections/<uuid:selection_pk>/confirm/",
        FreightOfferConfirmSelectionView.as_view(),
        name="freight_offer_selection_confirm",
    ),
    path(
        "freight-offers/selections/<uuid:selection_pk>/decline/",
        FreightOfferDeclineSelectionView.as_view(),
        name="freight_offer_selection_decline",
    ),
    path("driver-route-intents/", DriverRouteIntentListView.as_view(), name="driver_route_intents"),
    path(
        "driver-route-intents/new/",
        DriverRouteIntentCreateView.as_view(),
        name="driver_route_intent_create",
    ),
    path(
        "driver-route-intents/<uuid:pk>/",
        DriverRouteIntentDetailView.as_view(),
        name="driver_route_intent_detail",
    ),
    path(
        "driver-route-intents/<uuid:pk>/edit/",
        DriverRouteIntentUpdateView.as_view(),
        name="driver_route_intent_edit",
    ),
    path(
        "driver-route-intents/<uuid:pk>/activate/",
        DriverRouteIntentActivateView.as_view(),
        name="driver_route_intent_activate",
    ),
    path(
        "driver-route-intents/<uuid:pk>/cancel/",
        DriverRouteIntentCancelView.as_view(),
        name="driver_route_intent_cancel",
    ),
]
