from enum import StrEnum


class MatchEligibilityStatus(StrEnum):
    ELIGIBLE = "ELIGIBLE"
    INELIGIBLE = "INELIGIBLE"
    UNKNOWN = "UNKNOWN"


class MatchEligibilityReasonCode(StrEnum):
    ENTITY_INACTIVE = "ENTITY_INACTIVE"
    OUT_OF_SCOPE = "OUT_OF_SCOPE"
    COMPLIANCE_NOT_COMPLIANT = "COMPLIANCE_NOT_COMPLIANT"
    CARGO_PROFILE_INCOMPATIBLE = "CARGO_PROFILE_INCOMPATIBLE"
    VEHICLE_TYPE_INCOMPATIBLE = "VEHICLE_TYPE_INCOMPATIBLE"
    BODY_TYPE_INCOMPATIBLE = "BODY_TYPE_INCOMPATIBLE"
    TEMPERATURE_RANGE_INCOMPATIBLE = "TEMPERATURE_RANGE_INCOMPATIBLE"
    NO_COMPATIBLE_VEHICLE = "NO_COMPATIBLE_VEHICLE"
    NOT_AVAILABLE = "NOT_AVAILABLE"
    PRIVATE_TARGET_NOT_ALLOWED = "PRIVATE_TARGET_NOT_ALLOWED"
    INVALID_CANDIDATE_SHAPE = "INVALID_CANDIDATE_SHAPE"


class FreightOfferInvitationStatus(StrEnum):
    PENDING = "PENDING"
    SENT = "SENT"
    VIEWED = "VIEWED"
    DECLINED = "DECLINED"
    EXPIRED = "EXPIRED"
    CANCELLED = "CANCELLED"


class InvitationDeclineReason(StrEnum):
    PRICE_TOO_LOW = "PRICE_TOO_LOW"
    TOO_FAR = "TOO_FAR"
    VEHICLE_UNAVAILABLE = "VEHICLE_UNAVAILABLE"
    DRIVER_UNAVAILABLE = "DRIVER_UNAVAILABLE"
    ROUTE_NOT_INTERESTING = "ROUTE_NOT_INTERESTING"
    TIME_WINDOW = "TIME_WINDOW"
    CARGO_TYPE = "CARGO_TYPE"
    TEMPERATURE_REQUIREMENT = "TEMPERATURE_REQUIREMENT"
    RETURN_LOAD_REQUIRED = "RETURN_LOAD_REQUIRED"
    OTHER = "OTHER"


class MarketplaceEventType(StrEnum):
    OFFER_PUBLISHED = "offer_published"
    OFFER_IMPRESSION = "offer_impression"
    OFFER_OPENED = "offer_opened"
    OFFER_INVITED = "offer_invited"
    OFFER_INVITATION_VIEWED = "offer_invitation_viewed"
    OFFER_DECLINED = "offer_declined"
    OFFER_INTEREST_EXPRESSED = "offer_interest_expressed"
    OFFER_INTEREST_WITHDRAWN = "offer_interest_withdrawn"
    OFFER_CANDIDATE_SELECTED = "offer_candidate_selected"
    OFFER_SELECTION_CONFIRMED = "offer_selection_confirmed"
    OFFER_SELECTION_DECLINED = "offer_selection_declined"
    OFFER_SELECTION_EXPIRED = "offer_selection_expired"


class FreightOfferInterestStatus(StrEnum):
    ACTIVE = "ACTIVE"
    WITHDRAWN = "WITHDRAWN"
    NOT_SELECTED = "NOT_SELECTED"
    SELECTED = "SELECTED"
    EXPIRED = "EXPIRED"
    CANCELLED = "CANCELLED"


class FreightOfferSelectionStatus(StrEnum):
    PENDING_CONFIRMATION = "PENDING_CONFIRMATION"
    CONFIRMED = "CONFIRMED"
    DECLINED = "DECLINED"
    EXPIRED = "EXPIRED"
    CANCELLED = "CANCELLED"


class SelectionDeclineReason(StrEnum):
    VEHICLE_UNAVAILABLE = "VEHICLE_UNAVAILABLE"
    DRIVER_UNAVAILABLE = "DRIVER_UNAVAILABLE"
    SCHEDULE_CONFLICT = "SCHEDULE_CONFLICT"
    PRICE_NOT_ACCEPTED = "PRICE_NOT_ACCEPTED"
    ROUTE_CHANGED = "ROUTE_CHANGED"
    OPERATIONAL_ISSUE = "OPERATIONAL_ISSUE"
    OTHER = "OTHER"
