from enum import StrEnum


class FreightQuoteStatus(StrEnum):
    DRAFT = "DRAFT"
    CALCULATED = "CALCULATED"
    UNDER_REVIEW = "UNDER_REVIEW"
    APPROVED = "APPROVED"
    SENT = "SENT"
    ACCEPTED = "ACCEPTED"
    REJECTED = "REJECTED"
    EXPIRED = "EXPIRED"
    CANCELLED = "CANCELLED"
    SUPERSEDED = "SUPERSEDED"


class FreightPricingMethod(StrEnum):
    MANUAL = "MANUAL"
    RULE_BASED = "RULE_BASED"
    AUTOMATED = "AUTOMATED"
    NEGOTIATED = "NEGOTIATED"


class FreightQuoteChargeType(StrEnum):
    BASE_FREIGHT = "BASE_FREIGHT"
    TOLL = "TOLL"
    REFRIGERATION_SURCHARGE = "REFRIGERATION_SURCHARGE"
    INSURANCE = "INSURANCE"
    LOADING_UNLOADING = "LOADING_UNLOADING"
    DAILY_RATE = "DAILY_RATE"
    DEMURRAGE = "DEMURRAGE"
    ADMIN_FEE = "ADMIN_FEE"
    DISCOUNT = "DISCOUNT"
    OTHER = "OTHER"
