# Generated by Django 5.2.17 on 2026-08-15 02:56

from django.db import migrations


PERMISSIONS = [
    ("users.view", "View users"),
    ("users.create", "Create users"),
    ("users.update", "Update users"),
    ("organizations.view", "View organizations"),
    ("organizations.manage", "Manage organizations"),
    ("memberships.view", "View memberships"),
    ("memberships.manage", "Manage memberships"),
    ("roles.manage", "Manage roles"),
    ("audit.view", "View audit logs"),
]

ROLES = [
    ("SYSTEM_ADMIN", "System admin"),
    ("COMPANY_ADMIN", "Company admin"),
    ("OPERATIONS_MANAGER", "Operations manager"),
    ("DISPATCHER", "Dispatcher"),
    ("FINANCIAL_MANAGER", "Financial manager"),
    ("FINANCIAL_ANALYST", "Financial analyst"),
    ("COMMERCIAL_MANAGER", "Commercial manager"),
    ("SALESPERSON", "Salesperson"),
    ("DRIVER", "Driver"),
    ("CUSTOMER", "Customer"),
    ("AUDITOR", "Auditor"),
    ("VIEWER", "Viewer"),
]

ROLE_PERMISSIONS = {
    "SYSTEM_ADMIN": [code for code, _name in PERMISSIONS],
    "COMPANY_ADMIN": [
        "users.view",
        "users.create",
        "users.update",
        "organizations.view",
        "organizations.manage",
        "memberships.view",
        "memberships.manage",
        "roles.manage",
        "audit.view",
    ],
    "OPERATIONS_MANAGER": ["users.view", "organizations.view", "memberships.view"],
    "AUDITOR": ["audit.view", "organizations.view", "memberships.view"],
    "VIEWER": ["organizations.view", "memberships.view"],
}


def seed_initial_rbac(apps, schema_editor):
    Permission = apps.get_model("identity", "Permission")
    Role = apps.get_model("identity", "Role")
    RolePermission = apps.get_model("identity", "RolePermission")

    permission_by_code = {}
    for code, name in PERMISSIONS:
        permission, _created = Permission.objects.update_or_create(
            code=code,
            defaults={"name": name},
        )
        permission_by_code[code] = permission

    role_by_code = {}
    for code, name in ROLES:
        role, _created = Role.objects.update_or_create(
            code=code,
            defaults={"name": name},
        )
        role_by_code[code] = role

    for role_code, permission_codes in ROLE_PERMISSIONS.items():
        role = role_by_code[role_code]
        for permission_code in permission_codes:
            RolePermission.objects.get_or_create(
                role=role,
                permission=permission_by_code[permission_code],
            )


def unseed_initial_rbac(apps, schema_editor):
    Permission = apps.get_model("identity", "Permission")
    Role = apps.get_model("identity", "Role")

    Role.objects.filter(code__in=[code for code, _name in ROLES]).delete()
    Permission.objects.filter(code__in=[code for code, _name in PERMISSIONS]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0002_initial"),
    ]

    operations = [
        migrations.RunPython(seed_initial_rbac, unseed_initial_rbac),
    ]
