# Generated by Django 5.2.17 on 2026-08-23 20:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IntelligenceAssessmentRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(db_index=True)),
                ('operation_id', models.UUIDField(db_index=True)),
                ('assessed_at', models.DateTimeField()),
                ('reference_time', models.DateTimeField()),
                ('risk_score', models.FloatField()),
                ('risk_level', models.CharField(max_length=10)),
                ('model_name', models.CharField(max_length=100)),
                ('model_version', models.CharField(max_length=20)),
                ('feature_schema_version', models.CharField(max_length=20)),
                ('recommendation_policy_version', models.CharField(max_length=20)),
                ('context_fingerprint', models.CharField(db_index=True, max_length=64)),
                ('feature_payload', models.JSONField()),
                ('risk_payload', models.JSONField()),
                ('recommendation_payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'intelligence_assessment_record',
                'ordering': ['-assessed_at'],
                'indexes': [models.Index(fields=['organization_id', 'assessed_at'], name='idx_intel_org_assessed'), models.Index(fields=['operation_id', 'assessed_at'], name='idx_intel_op_assessed'), models.Index(fields=['operation_id', 'context_fingerprint'], name='idx_intel_op_fingerprint')],
            },
        ),
    ]
