from dataclasses import dataclass

from src.identity.domain.enums import PermissionCode, RoleCode


@dataclass(frozen=True)
class PermissionDefinition:
    code: PermissionCode
    name: str
    description: str = ""


@dataclass(frozen=True)
class RoleDefinition:
    code: RoleCode
    name: str
    description: str = ""


PERMISSIONS: tuple[PermissionDefinition, ...] = (
    PermissionDefinition(PermissionCode.USERS_VIEW, "View users"),
    PermissionDefinition(PermissionCode.USERS_CREATE, "Create users"),
    PermissionDefinition(PermissionCode.USERS_UPDATE, "Update users"),
    PermissionDefinition(PermissionCode.ORGANIZATIONS_VIEW, "View organizations"),
    PermissionDefinition(PermissionCode.ORGANIZATIONS_MANAGE, "Manage organizations"),
    PermissionDefinition(PermissionCode.MEMBERSHIPS_VIEW, "View memberships"),
    PermissionDefinition(PermissionCode.MEMBERSHIPS_MANAGE, "Manage memberships"),
    PermissionDefinition(PermissionCode.ROLES_MANAGE, "Manage roles"),
    PermissionDefinition(PermissionCode.AUDIT_VIEW, "View audit logs"),
    PermissionDefinition(PermissionCode.DRIVERS_VIEW, "View drivers"),
    PermissionDefinition(PermissionCode.DRIVERS_CREATE, "Create drivers"),
    PermissionDefinition(PermissionCode.DRIVERS_UPDATE, "Update drivers"),
    PermissionDefinition(PermissionCode.DRIVERS_APPROVE, "Approve drivers"),
    PermissionDefinition(PermissionCode.DRIVERS_CHANGE_STATUS, "Change driver status"),
    PermissionDefinition(PermissionCode.DRIVERS_MANAGE_DOCUMENTS, "Manage driver documents"),
    PermissionDefinition(PermissionCode.DRIVERS_ASSIGN_VEHICLE, "Assign driver vehicle"),
    PermissionDefinition(PermissionCode.DRIVERS_ASSIGN_CARRIER, "Assign driver carrier"),
    PermissionDefinition(PermissionCode.VEHICLES_VIEW, "View vehicles"),
    PermissionDefinition(PermissionCode.VEHICLES_CREATE, "Create vehicles"),
    PermissionDefinition(PermissionCode.VEHICLES_UPDATE, "Update vehicles"),
    PermissionDefinition(PermissionCode.VEHICLES_CHANGE_STATUS, "Change vehicle status"),
    PermissionDefinition(PermissionCode.VEHICLES_ASSIGN_DRIVER, "Assign vehicle driver"),
    PermissionDefinition(PermissionCode.VEHICLES_ASSIGN_CARRIER, "Assign vehicle carrier"),
    PermissionDefinition(PermissionCode.VEHICLES_MANAGE_DOCUMENTS, "Manage vehicle documents"),
    PermissionDefinition(
        PermissionCode.VEHICLES_MANAGE_REFRIGERATION, "Manage vehicle refrigeration profile"
    ),
    PermissionDefinition(PermissionCode.CUSTOMERS_VIEW, "View customers"),
    PermissionDefinition(PermissionCode.CUSTOMERS_CREATE, "Create customers"),
    PermissionDefinition(PermissionCode.CUSTOMERS_UPDATE, "Update customers"),
    PermissionDefinition(PermissionCode.CUSTOMERS_CHANGE_STATUS, "Change customer status"),
    PermissionDefinition(PermissionCode.CUSTOMERS_ASSIGN_OWNER, "Assign customer owner"),
    PermissionDefinition(PermissionCode.CARRIERS_VIEW, "View carriers"),
    PermissionDefinition(PermissionCode.CARRIERS_CREATE, "Create carriers"),
    PermissionDefinition(PermissionCode.CARRIERS_UPDATE, "Update carriers"),
    PermissionDefinition(PermissionCode.CARRIERS_CHANGE_STATUS, "Change carrier status"),
    PermissionDefinition(PermissionCode.CARRIERS_ASSIGN_OWNER, "Assign carrier owner"),
    PermissionDefinition(PermissionCode.CARRIERS_MANAGE_DRIVERS, "Manage carrier drivers"),
    PermissionDefinition(PermissionCode.CARRIERS_MANAGE_VEHICLES, "Manage carrier vehicles"),
    PermissionDefinition(PermissionCode.CARRIERS_MANAGE_DOCUMENTS, "Manage carrier documents"),
    PermissionDefinition(PermissionCode.DOCUMENTS_VIEW, "View documents"),
    PermissionDefinition(PermissionCode.DOCUMENTS_UPLOAD, "Upload documents"),
    PermissionDefinition(PermissionCode.DOCUMENTS_DOWNLOAD, "Download documents"),
    PermissionDefinition(PermissionCode.DOCUMENTS_REVIEW, "Review documents"),
    PermissionDefinition(PermissionCode.DOCUMENTS_APPROVE, "Approve documents"),
    PermissionDefinition(PermissionCode.DOCUMENTS_REJECT, "Reject documents"),
    PermissionDefinition(PermissionCode.DOCUMENTS_REPLACE, "Replace documents"),
    PermissionDefinition(PermissionCode.COMPLIANCE_VIEW, "View compliance"),
    PermissionDefinition(PermissionCode.COMPLIANCE_MANAGE, "Manage compliance"),
    PermissionDefinition(PermissionCode.FREIGHT_REQUESTS_VIEW, "View freight requests"),
    PermissionDefinition(PermissionCode.FREIGHT_REQUESTS_CREATE, "Create freight requests"),
    PermissionDefinition(PermissionCode.FREIGHT_REQUESTS_UPDATE, "Update freight requests"),
    PermissionDefinition(PermissionCode.FREIGHT_REQUESTS_SUBMIT, "Submit freight requests"),
    PermissionDefinition(
        PermissionCode.FREIGHT_REQUESTS_CHANGE_STATUS, "Change freight request status"
    ),
    PermissionDefinition(PermissionCode.FREIGHT_REQUESTS_CANCEL, "Cancel freight requests"),
    PermissionDefinition(
        PermissionCode.FREIGHT_REQUESTS_ASSIGN_OWNER, "Assign freight request owner"
    ),
    PermissionDefinition(PermissionCode.FREIGHT_QUOTES_VIEW, "View freight quotes"),
    PermissionDefinition(PermissionCode.FREIGHT_QUOTES_CREATE, "Create freight quotes"),
    PermissionDefinition(PermissionCode.FREIGHT_QUOTES_UPDATE, "Update freight quotes"),
    PermissionDefinition(PermissionCode.FREIGHT_QUOTES_REVIEW, "Review freight quotes"),
    PermissionDefinition(PermissionCode.FREIGHT_QUOTES_APPROVE, "Approve freight quotes"),
    PermissionDefinition(PermissionCode.FREIGHT_QUOTES_SEND, "Send freight quotes"),
    PermissionDefinition(PermissionCode.FREIGHT_QUOTES_REJECT, "Reject freight quotes"),
    PermissionDefinition(PermissionCode.FREIGHT_QUOTES_CANCEL, "Cancel freight quotes"),
    PermissionDefinition(PermissionCode.FREIGHT_QUOTES_REVISE, "Revise freight quotes"),
    PermissionDefinition(PermissionCode.FREIGHT_QUOTES_VIEW_MARGIN, "View freight quote margin"),
    PermissionDefinition(PermissionCode.FREIGHT_OFFERS_VIEW, "View freight offers"),
    PermissionDefinition(PermissionCode.FREIGHT_OFFERS_CREATE, "Create freight offers"),
    PermissionDefinition(PermissionCode.FREIGHT_OFFERS_UPDATE, "Update freight offers"),
    PermissionDefinition(PermissionCode.FREIGHT_OFFERS_PUBLISH, "Publish freight offers"),
    PermissionDefinition(PermissionCode.FREIGHT_OFFERS_PAUSE, "Pause freight offers"),
    PermissionDefinition(PermissionCode.FREIGHT_OFFERS_CANCEL, "Cancel freight offers"),
    PermissionDefinition(
        PermissionCode.FREIGHT_OFFERS_MANAGE_TARGETS, "Manage freight offer targets"
    ),
    PermissionDefinition(PermissionCode.FREIGHT_OFFERS_VIEW_MARGIN, "View freight offer margin"),
    PermissionDefinition(PermissionCode.FREIGHT_MATCHING_VIEW, "View freight matching"),
    PermissionDefinition(PermissionCode.FREIGHT_MATCHING_GENERATE, "Generate freight matching"),
    PermissionDefinition(PermissionCode.FREIGHT_MATCHING_INVITE, "Invite freight match candidates"),
    PermissionDefinition(
        PermissionCode.FREIGHT_MATCHING_VIEW_EXPLANATION, "View freight matching explanation"
    ),
    PermissionDefinition(PermissionCode.DRIVER_ROUTE_INTENTS_VIEW, "View driver route intents"),
    PermissionDefinition(PermissionCode.DRIVER_ROUTE_INTENTS_CREATE, "Create driver route intents"),
    PermissionDefinition(PermissionCode.DRIVER_ROUTE_INTENTS_UPDATE, "Update driver route intents"),
    PermissionDefinition(PermissionCode.DRIVER_ROUTE_INTENTS_CANCEL, "Cancel driver route intents"),
    PermissionDefinition(
        PermissionCode.FREIGHT_MARKETPLACE_INTEREST_VIEW, "View marketplace interest"
    ),
    PermissionDefinition(
        PermissionCode.FREIGHT_MARKETPLACE_SELECTION_VIEW, "View marketplace selection"
    ),
    PermissionDefinition(PermissionCode.FREIGHT_MARKETPLACE_SELECT, "Select candidate"),
    PermissionDefinition(PermissionCode.FREIGHT_MARKETPLACE_CANCEL_SELECTION, "Cancel selection"),
    PermissionDefinition(PermissionCode.FREIGHT_OPERATIONS_VIEW, "View freight operations"),
    PermissionDefinition(PermissionCode.FREIGHT_OPERATIONS_CREATE, "Create freight operations"),
    PermissionDefinition(PermissionCode.FREIGHT_OPERATIONS_CHANGE_STATUS, "Change freight operation status"),
    PermissionDefinition(PermissionCode.FREIGHT_OPERATIONS_REPORT_INCIDENT, "Report incident on freight operation"),
    PermissionDefinition(PermissionCode.FREIGHT_OPERATIONS_CANCEL, "Cancel freight operation"),
    PermissionDefinition(PermissionCode.FREIGHT_OPERATIONS_RECORD_POD, "Record proof of delivery for freight operation"),
    PermissionDefinition(PermissionCode.LOADS_VIEW, "View loads"),
)

ROLES: tuple[RoleDefinition, ...] = (
    RoleDefinition(RoleCode.SYSTEM_ADMIN, "System admin"),
    RoleDefinition(RoleCode.COMPANY_ADMIN, "Company admin"),
    RoleDefinition(RoleCode.OPERATIONS_MANAGER, "Operations manager"),
    RoleDefinition(RoleCode.DISPATCHER, "Dispatcher"),
    RoleDefinition(RoleCode.FINANCIAL_MANAGER, "Financial manager"),
    RoleDefinition(RoleCode.FINANCIAL_ANALYST, "Financial analyst"),
    RoleDefinition(RoleCode.COMMERCIAL_MANAGER, "Commercial manager"),
    RoleDefinition(RoleCode.SALESPERSON, "Salesperson"),
    RoleDefinition(RoleCode.DRIVER, "Driver"),
    RoleDefinition(RoleCode.CUSTOMER, "Customer"),
    RoleDefinition(RoleCode.AUDITOR, "Auditor"),
    RoleDefinition(RoleCode.VIEWER, "Viewer"),
)

ROLE_PERMISSIONS: dict[RoleCode, tuple[PermissionCode, ...]] = {
    RoleCode.SYSTEM_ADMIN: tuple(permission.code for permission in PERMISSIONS),
    RoleCode.COMPANY_ADMIN: (
        PermissionCode.USERS_VIEW,
        PermissionCode.USERS_CREATE,
        PermissionCode.USERS_UPDATE,
        PermissionCode.ORGANIZATIONS_VIEW,
        PermissionCode.ORGANIZATIONS_MANAGE,
        PermissionCode.MEMBERSHIPS_VIEW,
        PermissionCode.MEMBERSHIPS_MANAGE,
        PermissionCode.ROLES_MANAGE,
        PermissionCode.AUDIT_VIEW,
        PermissionCode.DRIVERS_VIEW,
        PermissionCode.DRIVERS_CREATE,
        PermissionCode.DRIVERS_UPDATE,
        PermissionCode.DRIVERS_APPROVE,
        PermissionCode.DRIVERS_CHANGE_STATUS,
        PermissionCode.DRIVERS_MANAGE_DOCUMENTS,
        PermissionCode.DRIVERS_ASSIGN_VEHICLE,
        PermissionCode.DRIVERS_ASSIGN_CARRIER,
        PermissionCode.VEHICLES_VIEW,
        PermissionCode.VEHICLES_CREATE,
        PermissionCode.VEHICLES_UPDATE,
        PermissionCode.VEHICLES_CHANGE_STATUS,
        PermissionCode.VEHICLES_ASSIGN_DRIVER,
        PermissionCode.VEHICLES_ASSIGN_CARRIER,
        PermissionCode.VEHICLES_MANAGE_DOCUMENTS,
        PermissionCode.VEHICLES_MANAGE_REFRIGERATION,
        PermissionCode.CUSTOMERS_VIEW,
        PermissionCode.CUSTOMERS_CREATE,
        PermissionCode.CUSTOMERS_UPDATE,
        PermissionCode.CUSTOMERS_CHANGE_STATUS,
        PermissionCode.CUSTOMERS_ASSIGN_OWNER,
        PermissionCode.CARRIERS_VIEW,
        PermissionCode.CARRIERS_CREATE,
        PermissionCode.CARRIERS_UPDATE,
        PermissionCode.CARRIERS_CHANGE_STATUS,
        PermissionCode.CARRIERS_ASSIGN_OWNER,
        PermissionCode.CARRIERS_MANAGE_DRIVERS,
        PermissionCode.CARRIERS_MANAGE_VEHICLES,
        PermissionCode.CARRIERS_MANAGE_DOCUMENTS,
        PermissionCode.DOCUMENTS_VIEW,
        PermissionCode.DOCUMENTS_UPLOAD,
        PermissionCode.DOCUMENTS_DOWNLOAD,
        PermissionCode.DOCUMENTS_REVIEW,
        PermissionCode.DOCUMENTS_APPROVE,
        PermissionCode.DOCUMENTS_REJECT,
        PermissionCode.DOCUMENTS_REPLACE,
        PermissionCode.COMPLIANCE_VIEW,
        PermissionCode.COMPLIANCE_MANAGE,
        PermissionCode.FREIGHT_REQUESTS_VIEW,
        PermissionCode.FREIGHT_REQUESTS_CREATE,
        PermissionCode.FREIGHT_REQUESTS_UPDATE,
        PermissionCode.FREIGHT_REQUESTS_SUBMIT,
        PermissionCode.FREIGHT_REQUESTS_CHANGE_STATUS,
        PermissionCode.FREIGHT_REQUESTS_CANCEL,
        PermissionCode.FREIGHT_REQUESTS_ASSIGN_OWNER,
        PermissionCode.FREIGHT_QUOTES_VIEW,
        PermissionCode.FREIGHT_QUOTES_CREATE,
        PermissionCode.FREIGHT_QUOTES_UPDATE,
        PermissionCode.FREIGHT_QUOTES_REVIEW,
        PermissionCode.FREIGHT_QUOTES_APPROVE,
        PermissionCode.FREIGHT_QUOTES_SEND,
        PermissionCode.FREIGHT_QUOTES_REJECT,
        PermissionCode.FREIGHT_QUOTES_CANCEL,
        PermissionCode.FREIGHT_QUOTES_REVISE,
        PermissionCode.FREIGHT_QUOTES_VIEW_MARGIN,
        PermissionCode.FREIGHT_OFFERS_VIEW,
        PermissionCode.FREIGHT_OFFERS_CREATE,
        PermissionCode.FREIGHT_OFFERS_UPDATE,
        PermissionCode.FREIGHT_OFFERS_PUBLISH,
        PermissionCode.FREIGHT_OFFERS_PAUSE,
        PermissionCode.FREIGHT_OFFERS_CANCEL,
        PermissionCode.FREIGHT_OFFERS_MANAGE_TARGETS,
        PermissionCode.FREIGHT_OFFERS_VIEW_MARGIN,
        PermissionCode.FREIGHT_MATCHING_VIEW,
        PermissionCode.FREIGHT_MATCHING_GENERATE,
        PermissionCode.FREIGHT_MATCHING_INVITE,
        PermissionCode.FREIGHT_MATCHING_VIEW_EXPLANATION,
        PermissionCode.DRIVER_ROUTE_INTENTS_VIEW,
        PermissionCode.DRIVER_ROUTE_INTENTS_CREATE,
        PermissionCode.DRIVER_ROUTE_INTENTS_UPDATE,
        PermissionCode.DRIVER_ROUTE_INTENTS_CANCEL,
        PermissionCode.FREIGHT_MARKETPLACE_INTEREST_VIEW,
        PermissionCode.FREIGHT_MARKETPLACE_SELECTION_VIEW,
        PermissionCode.FREIGHT_MARKETPLACE_SELECT,
        PermissionCode.FREIGHT_MARKETPLACE_CANCEL_SELECTION,
        PermissionCode.LOADS_VIEW,
    ),
    RoleCode.COMMERCIAL_MANAGER: (
        PermissionCode.ORGANIZATIONS_VIEW,
        PermissionCode.CUSTOMERS_VIEW,
        PermissionCode.CUSTOMERS_CREATE,
        PermissionCode.CUSTOMERS_UPDATE,
        PermissionCode.CUSTOMERS_CHANGE_STATUS,
        PermissionCode.CUSTOMERS_ASSIGN_OWNER,
        PermissionCode.FREIGHT_REQUESTS_VIEW,
        PermissionCode.FREIGHT_REQUESTS_CREATE,
        PermissionCode.FREIGHT_REQUESTS_UPDATE,
        PermissionCode.FREIGHT_REQUESTS_SUBMIT,
        PermissionCode.FREIGHT_REQUESTS_CANCEL,
        PermissionCode.FREIGHT_REQUESTS_ASSIGN_OWNER,
        PermissionCode.FREIGHT_QUOTES_VIEW,
        PermissionCode.FREIGHT_QUOTES_CREATE,
        PermissionCode.FREIGHT_QUOTES_UPDATE,
        PermissionCode.FREIGHT_QUOTES_REVIEW,
        PermissionCode.FREIGHT_QUOTES_APPROVE,
        PermissionCode.FREIGHT_QUOTES_SEND,
        PermissionCode.FREIGHT_QUOTES_REJECT,
        PermissionCode.FREIGHT_QUOTES_CANCEL,
        PermissionCode.FREIGHT_QUOTES_REVISE,
        PermissionCode.FREIGHT_QUOTES_VIEW_MARGIN,
        PermissionCode.FREIGHT_OFFERS_VIEW,
        PermissionCode.FREIGHT_OFFERS_CREATE,
        PermissionCode.FREIGHT_OFFERS_UPDATE,
    ),
    RoleCode.SALESPERSON: (
        PermissionCode.ORGANIZATIONS_VIEW,
        PermissionCode.CUSTOMERS_VIEW,
        PermissionCode.CUSTOMERS_CREATE,
        PermissionCode.CUSTOMERS_UPDATE,
        PermissionCode.FREIGHT_REQUESTS_VIEW,
        PermissionCode.FREIGHT_REQUESTS_CREATE,
        PermissionCode.FREIGHT_REQUESTS_UPDATE,
        PermissionCode.FREIGHT_REQUESTS_SUBMIT,
        PermissionCode.FREIGHT_QUOTES_VIEW,
        PermissionCode.FREIGHT_QUOTES_CREATE,
        PermissionCode.FREIGHT_QUOTES_UPDATE,
        PermissionCode.FREIGHT_QUOTES_SEND,
        PermissionCode.FREIGHT_OFFERS_VIEW,
        PermissionCode.FREIGHT_MARKETPLACE_INTEREST_VIEW,
        PermissionCode.FREIGHT_MARKETPLACE_SELECTION_VIEW,
    ),
    RoleCode.OPERATIONS_MANAGER: (
        PermissionCode.USERS_VIEW,
        PermissionCode.ORGANIZATIONS_VIEW,
        PermissionCode.MEMBERSHIPS_VIEW,
        PermissionCode.DRIVERS_VIEW,
        PermissionCode.DRIVERS_CREATE,
        PermissionCode.DRIVERS_UPDATE,
        PermissionCode.DRIVERS_APPROVE,
        PermissionCode.DRIVERS_CHANGE_STATUS,
        PermissionCode.DRIVERS_MANAGE_DOCUMENTS,
        PermissionCode.DRIVERS_ASSIGN_VEHICLE,
        PermissionCode.DRIVERS_ASSIGN_CARRIER,
        PermissionCode.VEHICLES_VIEW,
        PermissionCode.VEHICLES_CREATE,
        PermissionCode.VEHICLES_UPDATE,
        PermissionCode.VEHICLES_CHANGE_STATUS,
        PermissionCode.VEHICLES_ASSIGN_DRIVER,
        PermissionCode.VEHICLES_ASSIGN_CARRIER,
        PermissionCode.VEHICLES_MANAGE_DOCUMENTS,
        PermissionCode.VEHICLES_MANAGE_REFRIGERATION,
        PermissionCode.CARRIERS_VIEW,
        PermissionCode.CARRIERS_CREATE,
        PermissionCode.CARRIERS_UPDATE,
        PermissionCode.CARRIERS_CHANGE_STATUS,
        PermissionCode.CARRIERS_ASSIGN_OWNER,
        PermissionCode.CARRIERS_MANAGE_DRIVERS,
        PermissionCode.CARRIERS_MANAGE_VEHICLES,
        PermissionCode.CARRIERS_MANAGE_DOCUMENTS,
        PermissionCode.DOCUMENTS_VIEW,
        PermissionCode.DOCUMENTS_UPLOAD,
        PermissionCode.DOCUMENTS_DOWNLOAD,
        PermissionCode.DOCUMENTS_REVIEW,
        PermissionCode.DOCUMENTS_APPROVE,
        PermissionCode.DOCUMENTS_REJECT,
        PermissionCode.DOCUMENTS_REPLACE,
        PermissionCode.COMPLIANCE_VIEW,
        PermissionCode.COMPLIANCE_MANAGE,
        PermissionCode.FREIGHT_REQUESTS_VIEW,
        PermissionCode.FREIGHT_REQUESTS_CREATE,
        PermissionCode.FREIGHT_REQUESTS_UPDATE,
        PermissionCode.FREIGHT_REQUESTS_SUBMIT,
        PermissionCode.FREIGHT_REQUESTS_CHANGE_STATUS,
        PermissionCode.FREIGHT_REQUESTS_CANCEL,
        PermissionCode.FREIGHT_REQUESTS_ASSIGN_OWNER,
        PermissionCode.FREIGHT_QUOTES_VIEW,
        PermissionCode.FREIGHT_QUOTES_CREATE,
        PermissionCode.FREIGHT_QUOTES_UPDATE,
        PermissionCode.FREIGHT_QUOTES_REVIEW,
        PermissionCode.FREIGHT_QUOTES_APPROVE,
        PermissionCode.FREIGHT_QUOTES_SEND,
        PermissionCode.FREIGHT_QUOTES_REJECT,
        PermissionCode.FREIGHT_QUOTES_CANCEL,
        PermissionCode.FREIGHT_QUOTES_REVISE,
        PermissionCode.FREIGHT_OFFERS_VIEW,
        PermissionCode.FREIGHT_OFFERS_CREATE,
        PermissionCode.FREIGHT_OFFERS_UPDATE,
        PermissionCode.FREIGHT_OFFERS_PUBLISH,
        PermissionCode.FREIGHT_OFFERS_PAUSE,
        PermissionCode.FREIGHT_OFFERS_CANCEL,
        PermissionCode.FREIGHT_OFFERS_MANAGE_TARGETS,
        PermissionCode.FREIGHT_MATCHING_VIEW,
        PermissionCode.FREIGHT_MATCHING_GENERATE,
        PermissionCode.FREIGHT_MATCHING_INVITE,
        PermissionCode.FREIGHT_MATCHING_VIEW_EXPLANATION,
        PermissionCode.DRIVER_ROUTE_INTENTS_VIEW,
        PermissionCode.DRIVER_ROUTE_INTENTS_CREATE,
        PermissionCode.DRIVER_ROUTE_INTENTS_UPDATE,
        PermissionCode.DRIVER_ROUTE_INTENTS_CANCEL,
        PermissionCode.FREIGHT_MARKETPLACE_INTEREST_VIEW,
        PermissionCode.FREIGHT_MARKETPLACE_SELECTION_VIEW,
        PermissionCode.FREIGHT_MARKETPLACE_SELECT,
        PermissionCode.FREIGHT_MARKETPLACE_CANCEL_SELECTION,
        PermissionCode.FREIGHT_OPERATIONS_VIEW,
        PermissionCode.FREIGHT_OPERATIONS_CREATE,
        PermissionCode.FREIGHT_OPERATIONS_CHANGE_STATUS,
        PermissionCode.FREIGHT_OPERATIONS_REPORT_INCIDENT,
        PermissionCode.FREIGHT_OPERATIONS_CANCEL,
        PermissionCode.FREIGHT_OPERATIONS_RECORD_POD,
        PermissionCode.LOADS_VIEW,
    ),
    RoleCode.DISPATCHER: (
        PermissionCode.ORGANIZATIONS_VIEW,
        PermissionCode.DRIVERS_VIEW,
        PermissionCode.VEHICLES_VIEW,
        PermissionCode.FREIGHT_REQUESTS_VIEW,
        PermissionCode.FREIGHT_REQUESTS_CHANGE_STATUS,
        PermissionCode.FREIGHT_QUOTES_VIEW,
        PermissionCode.FREIGHT_OFFERS_VIEW,
        PermissionCode.FREIGHT_OFFERS_CREATE,
        PermissionCode.FREIGHT_OFFERS_UPDATE,
        PermissionCode.FREIGHT_OFFERS_PUBLISH,
        PermissionCode.FREIGHT_OFFERS_PAUSE,
        PermissionCode.FREIGHT_OFFERS_CANCEL,
        PermissionCode.FREIGHT_OFFERS_MANAGE_TARGETS,
        PermissionCode.FREIGHT_MATCHING_VIEW,
        PermissionCode.FREIGHT_MATCHING_GENERATE,
        PermissionCode.FREIGHT_MATCHING_INVITE,
        PermissionCode.FREIGHT_MATCHING_VIEW_EXPLANATION,
        PermissionCode.DRIVER_ROUTE_INTENTS_VIEW,
        PermissionCode.DRIVER_ROUTE_INTENTS_CREATE,
        PermissionCode.DRIVER_ROUTE_INTENTS_UPDATE,
        PermissionCode.FREIGHT_OPERATIONS_VIEW,
        PermissionCode.FREIGHT_OPERATIONS_CHANGE_STATUS,
        PermissionCode.FREIGHT_OPERATIONS_REPORT_INCIDENT,
        PermissionCode.FREIGHT_OPERATIONS_CANCEL,
        PermissionCode.FREIGHT_OPERATIONS_RECORD_POD,
        PermissionCode.FREIGHT_MARKETPLACE_INTEREST_VIEW,
        PermissionCode.FREIGHT_MARKETPLACE_SELECTION_VIEW,
        PermissionCode.FREIGHT_MARKETPLACE_SELECT,
        PermissionCode.FREIGHT_MARKETPLACE_CANCEL_SELECTION,
        PermissionCode.LOADS_VIEW,
    ),
    RoleCode.FINANCIAL_MANAGER: (
        PermissionCode.ORGANIZATIONS_VIEW,
        PermissionCode.AUDIT_VIEW,
        PermissionCode.FREIGHT_QUOTES_VIEW,
        PermissionCode.FREIGHT_QUOTES_VIEW_MARGIN,
        PermissionCode.FREIGHT_OFFERS_VIEW,
        PermissionCode.FREIGHT_OFFERS_VIEW_MARGIN,
    ),
    RoleCode.FINANCIAL_ANALYST: (
        PermissionCode.ORGANIZATIONS_VIEW,
        PermissionCode.FREIGHT_QUOTES_VIEW,
        PermissionCode.FREIGHT_QUOTES_VIEW_MARGIN,
        PermissionCode.FREIGHT_OFFERS_VIEW,
        PermissionCode.FREIGHT_OFFERS_VIEW_MARGIN,
    ),
    RoleCode.AUDITOR: (
        PermissionCode.AUDIT_VIEW,
        PermissionCode.ORGANIZATIONS_VIEW,
        PermissionCode.MEMBERSHIPS_VIEW,
        PermissionCode.DRIVERS_VIEW,
        PermissionCode.VEHICLES_VIEW,
        PermissionCode.CARRIERS_VIEW,
        PermissionCode.DOCUMENTS_VIEW,
        PermissionCode.DOCUMENTS_DOWNLOAD,
        PermissionCode.COMPLIANCE_VIEW,
        PermissionCode.FREIGHT_REQUESTS_VIEW,
        PermissionCode.FREIGHT_QUOTES_VIEW,
        PermissionCode.FREIGHT_OFFERS_VIEW,
        PermissionCode.FREIGHT_MATCHING_VIEW,
        PermissionCode.FREIGHT_MATCHING_VIEW_EXPLANATION,
        PermissionCode.DRIVER_ROUTE_INTENTS_VIEW,
        PermissionCode.FREIGHT_MARKETPLACE_INTEREST_VIEW,
        PermissionCode.FREIGHT_MARKETPLACE_SELECTION_VIEW,
    ),
    RoleCode.VIEWER: (
        PermissionCode.ORGANIZATIONS_VIEW,
        PermissionCode.MEMBERSHIPS_VIEW,
        PermissionCode.DRIVERS_VIEW,
        PermissionCode.VEHICLES_VIEW,
    ),
}
