# Generated by Django 5.2.17 on 2026-08-15 14:34

import django.db.models.deletion
import src.customers.domain.enums
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_type', models.CharField(blank=True, choices=[('INDIVIDUAL', 'INDIVIDUAL'), ('COMPANY', 'COMPANY')], default=src.customers.domain.enums.CustomerType['COMPANY'], max_length=20)),
                ('legal_name', models.CharField(max_length=180)),
                ('trade_name', models.CharField(blank=True, max_length=180)),
                ('document_number', models.CharField(max_length=40)),
                ('state_registration', models.CharField(blank=True, max_length=40)),
                ('municipal_registration', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('mobile_phone', models.CharField(blank=True, max_length=40)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('street', models.CharField(blank=True, max_length=180)),
                ('number', models.CharField(blank=True, max_length=20)),
                ('complement', models.CharField(blank=True, max_length=180)),
                ('district', models.CharField(blank=True, max_length=80)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('state', models.CharField(blank=True, max_length=2)),
                ('country', models.CharField(blank=True, default='BR', max_length=2)),
                ('status', models.CharField(blank=True, choices=[('PROSPECT', 'PROSPECT'), ('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE'), ('BLOCKED', 'BLOCKED')], default=src.customers.domain.enums.CustomerStatus['PROSPECT'], max_length=20)),
                ('business_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='organizations.businessunit')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='organizations.organization')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_customers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['legal_name'],
                'indexes': [models.Index(fields=['organization', 'document_number'], name='customers_c_organiz_459676_idx'), models.Index(fields=['organization', 'status'], name='customers_c_organiz_628fa0_idx'), models.Index(fields=['owner'], name='customers_c_owner_i_5773d3_idx'), models.Index(fields=['created_at'], name='customers_c_created_1ed0f4_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'document_number'), name='unique_customer_document_per_organization')],
            },
        ),
    ]
