from typing import BinaryIO, Protocol


class DocumentStoragePort(Protocol):
    def save(self, path: str, content: BinaryIO) -> str: ...

    def delete(self, path: str) -> None: ...

    def exists(self, path: str) -> bool: ...

    def open(self, path: str, mode: str = "rb") -> BinaryIO: ...
