# Generated by Django 5.2.17 on 2026-08-15 12:05

import django.db.models.deletion
import src.drivers.domain.enums
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=180)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('document', models.CharField(blank=True, max_length=40)),
                ('driver_license_number', models.CharField(blank=True, max_length=60)),
                ('driver_license_category', models.CharField(blank=True, max_length=20)),
                ('driver_license_expiration', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('UNDER_REVIEW', 'UNDER_REVIEW'), ('APPROVED', 'APPROVED'), ('ACTIVE', 'ACTIVE'), ('SUSPENDED', 'SUSPENDED'), ('BLOCKED', 'BLOCKED'), ('INACTIVE', 'INACTIVE')], default=src.drivers.domain.enums.DriverStatus['PENDING'], max_length=20)),
                ('approval_status', models.CharField(choices=[('PENDING', 'PENDING'), ('UNDER_REVIEW', 'UNDER_REVIEW'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED'), ('SUSPENDED', 'SUSPENDED')], default=src.drivers.domain.enums.DriverApprovalStatus['PENDING'], max_length=20)),
                ('availability_status', models.CharField(choices=[('OFFLINE', 'OFFLINE'), ('AVAILABLE', 'AVAILABLE'), ('BUSY', 'BUSY'), ('PAUSED', 'PAUSED'), ('UNAVAILABLE', 'UNAVAILABLE')], default=src.drivers.domain.enums.DriverAvailabilityStatus['OFFLINE'], max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_drivers', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='drivers', to='organizations.organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='DriverDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('DRIVER_LICENSE', 'DRIVER_LICENSE'), ('ADDRESS_PROOF', 'ADDRESS_PROOF'), ('PERSONAL_DOCUMENT', 'PERSONAL_DOCUMENT'), ('CERTIFICATION', 'CERTIFICATION'), ('OTHER', 'OTHER')], max_length=40)),
                ('storage_key', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('UNDER_REVIEW', 'UNDER_REVIEW'), ('VERIFIED', 'VERIFIED'), ('REJECTED', 'REJECTED'), ('EXPIRED', 'EXPIRED')], default=src.drivers.domain.enums.DriverDocumentStatus['PENDING'], max_length=20)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='drivers.driver')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_driver_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['driver__full_name', 'document_type', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['organization', 'approval_status'], name='drivers_dri_organiz_355c53_idx'),
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['organization', 'availability_status'], name='drivers_dri_organiz_113119_idx'),
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['status'], name='drivers_dri_status_d7a5f5_idx'),
        ),
        migrations.AddConstraint(
            model_name='driver',
            constraint=models.UniqueConstraint(condition=models.Q(('document', ''), _negated=True), fields=('organization', 'document'), name='unique_driver_document_per_organization_when_present'),
        ),
        migrations.AddConstraint(
            model_name='driver',
            constraint=models.UniqueConstraint(condition=models.Q(('driver_license_number', ''), _negated=True), fields=('organization', 'driver_license_number'), name='unique_driver_license_per_organization_when_present'),
        ),
        migrations.AddIndex(
            model_name='driverdocument',
            index=models.Index(fields=['driver', 'status'], name='drivers_dri_driver__c25750_idx'),
        ),
        migrations.AddIndex(
            model_name='driverdocument',
            index=models.Index(fields=['document_type', 'status'], name='drivers_dri_documen_14b227_idx'),
        ),
        migrations.AddConstraint(
            model_name='driverdocument',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['PENDING', 'UNDER_REVIEW', 'VERIFIED'])), fields=('driver', 'document_type'), name='unique_active_driver_document_type'),
        ),
    ]
