# Generated by Django 5.2.17 on 2026-08-15 15:43

import src.drivers.domain.enums
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='city',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='driver',
            name='complement',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='driver',
            name='country',
            field=models.CharField(blank=True, default='BR', max_length=2),
        ),
        migrations.AddField(
            model_name='driver',
            name='district',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='driver',
            name='driver_license_issue_state',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='driver',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='driver',
            name='engagement_type',
            field=models.CharField(choices=[('OWNED', 'OWNED'), ('AGGREGATED', 'AGGREGATED'), ('CARRIER', 'CARRIER'), ('PARTNER', 'PARTNER')], default=src.drivers.domain.enums.DriverEngagementType['OWNED'], max_length=20),
        ),
        migrations.AddField(
            model_name='driver',
            name='mobile_phone',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='driver',
            name='number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='driver',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='driver',
            name='state',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='driver',
            name='street',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['organization', 'engagement_type'], name='drivers_dri_organiz_dc6f43_idx'),
        ),
    ]
