# Generated by Django 5.2.17 on 2026-08-15 17:02

import django.db.models.deletion
import src.compliance.domain.enums
from django.conf import settings
from django.db import migrations, models


def migrate_verified_to_approved(apps, schema_editor):
    DriverDocument = apps.get_model("drivers", "DriverDocument")
    DriverDocument.objects.filter(status="VERIFIED").update(status="APPROVED")


class Migration(migrations.Migration):

    dependencies = [
        ("drivers", "0002_driver_birth_date_driver_city_driver_complement_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="driverdocument",
            name="unique_active_driver_document_type",
        ),
        migrations.RenameField(
            model_name="driverdocument",
            old_name="verified_at",
            new_name="reviewed_at",
        ),
        migrations.RenameField(
            model_name="driverdocument",
            old_name="verified_by",
            new_name="reviewed_by",
        ),
        migrations.AddField(
            model_name="driverdocument",
            name="content_hash",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="driverdocument",
            name="issue_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="driverdocument",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="driverdocument",
            name="original_filename",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="driverdocument",
            name="replaced_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="replaces",
                to="drivers.driverdocument",
            ),
        ),
        migrations.AlterField(
            model_name="driverdocument",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_driver_documents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="driverdocument",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("DRIVER_LICENSE", "DRIVER_LICENSE"),
                    ("ADDRESS_PROOF", "ADDRESS_PROOF"),
                    ("PERSONAL_DOCUMENT", "PERSONAL_DOCUMENT"),
                    ("CERTIFICATION", "CERTIFICATION"),
                    ("COURSE", "COURSE"),
                    ("OPERATIONAL_EXAM", "OPERATIONAL_EXAM"),
                    ("OTHER", "OTHER"),
                ],
                max_length=40,
            ),
        ),
        migrations.RunPython(migrate_verified_to_approved, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="driverdocument",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "PENDING"),
                    ("UNDER_REVIEW", "UNDER_REVIEW"),
                    ("APPROVED", "APPROVED"),
                    ("REJECTED", "REJECTED"),
                    ("EXPIRED", "EXPIRED"),
                    ("REPLACED", "REPLACED"),
                ],
                default=src.compliance.domain.enums.DocumentStatus["PENDING"],
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="driverdocument",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["PENDING", "UNDER_REVIEW", "APPROVED"])),
                fields=("driver", "document_type"),
                name="unique_active_driver_document_type",
            ),
        ),
    ]
