# Generated by Django 5.2.17 on 2026-08-15 18:46

import django.db.models.deletion
import src.drivers.domain.route_intent_enums
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0003_remove_driverdocument_unique_active_driver_document_type_and_more'),
        ('organizations', '0001_initial'),
        ('vehicles', '0003_rename_verified_at_vehicledocument_reviewed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverRouteIntent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('intent_type', models.CharField(choices=[('RETURN_LOAD', 'RETURN_LOAD'), ('DESTINATION_PREFERENCE', 'DESTINATION_PREFERENCE')], max_length=30)),
                ('origin_city', models.CharField(max_length=80)),
                ('origin_state', models.CharField(max_length=2)),
                ('destination_city', models.CharField(max_length=80)),
                ('destination_state', models.CharField(max_length=2)),
                ('available_from', models.DateTimeField()),
                ('available_until', models.DateTimeField()),
                ('max_origin_deviation_km', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('max_destination_deviation_km', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('cargo_preference', models.CharField(blank=True, choices=[('DRY_CARGO', 'DRY_CARGO'), ('REFRIGERATED_CARGO', 'REFRIGERATED_CARGO'), ('BOTH', 'BOTH')], max_length=30)),
                ('refrigeration_snapshot', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('DRAFT', 'DRAFT'), ('ACTIVE', 'ACTIVE'), ('EXPIRED', 'EXPIRED'), ('CANCELLED', 'CANCELLED'), ('COMPLETED', 'COMPLETED')], default=src.drivers.domain.route_intent_enums.DriverRouteIntentStatus['DRAFT'], max_length=20)),
                ('source', models.CharField(choices=[('BACKOFFICE', 'BACKOFFICE'), ('DRIVER_APP', 'DRIVER_APP'), ('SYSTEM', 'SYSTEM')], default=src.drivers.domain.route_intent_enums.DriverRouteIntentSource['BACKOFFICE'], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.TextField(blank=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_driver_route_intents', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_intents', to='drivers.driver')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='driver_route_intents', to='organizations.organization')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='route_intents', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-available_from', '-created_at'],
                'indexes': [models.Index(fields=['organization', 'status'], name='drivers_dri_organiz_35823e_idx'), models.Index(fields=['driver', 'status'], name='drivers_dri_driver__a79b97_idx'), models.Index(fields=['vehicle', 'status'], name='drivers_dri_vehicle_fe8874_idx'), models.Index(fields=['available_from', 'available_until'], name='drivers_dri_availab_cae18d_idx'), models.Index(fields=['origin_state', 'origin_city'], name='drivers_dri_origin__390dda_idx'), models.Index(fields=['destination_state', 'destination_city'], name='drivers_dri_destina_9ff6f5_idx')],
            },
        ),
    ]
