# Generated by Django 5.2.17 on 2026-08-18 07:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0004_driver_route_intent'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_city', models.CharField(blank=True, max_length=80)),
                ('base_state', models.CharField(blank=True, max_length=2)),
                ('base_postal_code', models.CharField(blank=True, max_length=20)),
                ('base_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('base_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('preferred_radius_km', models.PositiveIntegerField(blank=True, null=True)),
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='drivers.driver')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DriverRegionPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.CharField(max_length=80)),
                ('state', models.CharField(max_length=2)),
                ('preference_type', models.CharField(choices=[('PREFER', 'Preferida'), ('AVOID', 'Evitada')], default='PREFER', max_length=10)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region_preferences', to='drivers.driver')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('driver', 'city', 'state', 'preference_type'), name='unique_driver_region_preference')],
            },
        ),
    ]
