# Generated by Django 5.2.17 on 2026-08-15 12:05

import django.db.models.deletion
import src.vehicles.domain.enums
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plate', models.CharField(max_length=12)),
                ('vehicle_type', models.CharField(choices=[('MOTORCYCLE', 'MOTORCYCLE'), ('CAR', 'CAR'), ('UTILITY', 'UTILITY'), ('PICKUP', 'PICKUP'), ('VAN', 'VAN'), ('VUC', 'VUC'), ('TRUCK', 'TRUCK'), ('SEMI_TRUCK', 'SEMI_TRUCK'), ('TRAILER', 'TRAILER')], max_length=30)),
                ('ownership_type', models.CharField(choices=[('OWNED', 'OWNED'), ('AGGREGATED', 'AGGREGATED'), ('THIRD_PARTY', 'THIRD_PARTY'), ('AUTONOMOUS', 'AUTONOMOUS'), ('PARTNER', 'PARTNER')], default=src.vehicles.domain.enums.VehicleOwnershipType['OWNED'], max_length=30)),
                ('brand', models.CharField(blank=True, max_length=80)),
                ('model', models.CharField(blank=True, max_length=80)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=40)),
                ('capacity_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('capacity_volume_m3', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_length_m', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('max_width_m', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('max_height_m', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('refrigerated', models.BooleanField(default=False)),
                ('closed_box', models.BooleanField(default=False)),
                ('open_body', models.BooleanField(default=False)),
                ('tail_lift', models.BooleanField(default=False)),
                ('helper_available', models.BooleanField(default=False)),
                ('hazardous_compatible', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('ACTIVE', 'ACTIVE'), ('IN_MAINTENANCE', 'IN_MAINTENANCE'), ('SUSPENDED', 'SUSPENDED'), ('INACTIVE', 'INACTIVE')], default=src.vehicles.domain.enums.VehicleStatus['PENDING'], max_length=20)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='organizations.organization')),
            ],
            options={
                'ordering': ['plate'],
            },
        ),
        migrations.CreateModel(
            name='DriverVehicleAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('primary', models.BooleanField(default=False)),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_assignments', to='drivers.driver')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_assignments', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-active', '-primary', '-valid_from'],
            },
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['organization', 'status'], name='vehicles_ve_organiz_722bcb_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['vehicle_type'], name='vehicles_ve_vehicle_76fbe4_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['plate'], name='vehicles_ve_plate_f1ecfa_idx'),
        ),
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.UniqueConstraint(fields=('organization', 'plate'), name='unique_vehicle_plate_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.CheckConstraint(condition=models.Q(('capacity_weight_kg__gte', 0), ('capacity_weight_kg', None), _connector='OR'), name='vehicle_capacity_weight_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.CheckConstraint(condition=models.Q(('capacity_volume_m3__gte', 0), ('capacity_volume_m3', None), _connector='OR'), name='vehicle_capacity_volume_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.CheckConstraint(condition=models.Q(('max_length_m__gte', 0), ('max_length_m', None), _connector='OR'), name='vehicle_max_length_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.CheckConstraint(condition=models.Q(('max_width_m__gte', 0), ('max_width_m', None), _connector='OR'), name='vehicle_max_width_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.CheckConstraint(condition=models.Q(('max_height_m__gte', 0), ('max_height_m', None), _connector='OR'), name='vehicle_max_height_non_negative'),
        ),
        migrations.AddIndex(
            model_name='drivervehicleassignment',
            index=models.Index(fields=['driver', 'active'], name='vehicles_dr_driver__a22155_idx'),
        ),
        migrations.AddIndex(
            model_name='drivervehicleassignment',
            index=models.Index(fields=['vehicle', 'active'], name='vehicles_dr_vehicle_4d0096_idx'),
        ),
        migrations.AddConstraint(
            model_name='drivervehicleassignment',
            constraint=models.CheckConstraint(condition=models.Q(('valid_until', None), ('valid_until__gte', models.F('valid_from')), _connector='OR'), name='driver_vehicle_assignment_valid_period'),
        ),
        migrations.AddConstraint(
            model_name='drivervehicleassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True), ('primary', True)), fields=('driver',), name='unique_active_primary_vehicle_per_driver'),
        ),
        migrations.AddConstraint(
            model_name='drivervehicleassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True), ('primary', True)), fields=('vehicle',), name='unique_active_primary_driver_per_vehicle'),
        ),
        migrations.AddConstraint(
            model_name='drivervehicleassignment',
            constraint=models.UniqueConstraint(fields=('driver', 'vehicle', 'valid_from'), name='unique_driver_vehicle_assignment_start'),
        ),
    ]
