# Generated by Django 5.2.17 on 2026-08-15 15:57

import django.db.models.deletion
import src.vehicles.domain.enums
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RefrigerationProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('has_refrigeration_unit', models.BooleanField(default=True)),
                ('unit_manufacturer', models.CharField(blank=True, max_length=80)),
                ('unit_model', models.CharField(blank=True, max_length=80)),
                ('temperature_min_c', models.DecimalField(decimal_places=2, max_digits=5)),
                ('temperature_max_c', models.DecimalField(decimal_places=2, max_digits=5)),
                ('default_setpoint_c', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('control_type', models.CharField(choices=[('MANUAL', 'MANUAL'), ('DIGITAL', 'DIGITAL'), ('AUTOMATED', 'AUTOMATED')], default=src.vehicles.domain.enums.RefrigerationControlType['DIGITAL'], max_length=20)),
                ('last_maintenance_date', models.DateField(blank=True, null=True)),
                ('next_maintenance_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('CRLV', 'CRLV'), ('LICENCIAMENTO', 'LICENCIAMENTO'), ('SEGURO', 'SEGURO'), ('RNTRC', 'RNTRC'), ('CERTIFICADO', 'CERTIFICADO'), ('REFRIGERACAO', 'REFRIGERACAO'), ('CALIBRACAO', 'CALIBRACAO'), ('OUTRO', 'OUTRO')], max_length=30)),
                ('storage_key', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('VERIFIED', 'VERIFIED'), ('EXPIRED', 'EXPIRED')], default=src.vehicles.domain.enums.VehicleDocumentStatus['PENDING'], max_length=20)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['vehicle__plate', 'document_type', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='vehicle',
            name='body_type',
            field=models.CharField(blank=True, choices=[('BAU', 'BAU'), ('BAU_REFRIGERADO', 'BAU_REFRIGERADO'), ('SIDER', 'SIDER'), ('GRADE_BAIXA', 'GRADE_BAIXA'), ('GRANELEIRO', 'GRANELEIRO'), ('CACAMBA', 'CACAMBA'), ('PLATAFORMA', 'PLATAFORMA'), ('TANQUE', 'TANQUE'), ('CEGONHA', 'CEGONHA')], max_length=30),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='cargo_profile',
            field=models.CharField(choices=[('DRY_CARGO', 'DRY_CARGO'), ('REFRIGERATED_CARGO', 'REFRIGERATED_CARGO'), ('BOTH', 'BOTH')], default=src.vehicles.domain.enums.VehicleCargoProfile['DRY_CARGO'], max_length=30),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='chassis',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='gross_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='model_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='odometer_km',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='operational_status',
            field=models.CharField(choices=[('AVAILABLE', 'AVAILABLE'), ('ASSIGNED', 'ASSIGNED'), ('IN_TRANSIT', 'IN_TRANSIT'), ('MAINTENANCE', 'MAINTENANCE'), ('UNAVAILABLE', 'UNAVAILABLE')], default=src.vehicles.domain.enums.VehicleOperationalStatus['UNAVAILABLE'], max_length=20),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='renavam',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='state',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='ownership_type',
            field=models.CharField(choices=[('OWNED', 'OWNED'), ('AGGREGATED', 'AGGREGATED'), ('THIRD_PARTY', 'THIRD_PARTY'), ('AUTONOMOUS', 'AUTONOMOUS'), ('PARTNER', 'PARTNER'), ('SUBCONTRACTED', 'SUBCONTRACTED')], default=src.vehicles.domain.enums.VehicleOwnershipType['OWNED'], max_length=30),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('PENDING_APPROVAL', 'PENDING_APPROVAL'), ('ACTIVE', 'ACTIVE'), ('IN_MAINTENANCE', 'IN_MAINTENANCE'), ('INACTIVE', 'INACTIVE'), ('BLOCKED', 'BLOCKED'), ('SUSPENDED', 'SUSPENDED')], default=src.vehicles.domain.enums.VehicleStatus['PENDING_APPROVAL'], max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('MOTORCYCLE', 'MOTORCYCLE'), ('CAR', 'CAR'), ('UTILITY', 'UTILITY'), ('PICKUP', 'PICKUP'), ('SEMI_TRUCK', 'SEMI_TRUCK'), ('TRAILER', 'TRAILER'), ('MOTO', 'MOTO'), ('CARRO', 'CARRO'), ('UTILITARIO', 'UTILITARIO'), ('VAN', 'VAN'), ('VUC', 'VUC'), ('TOCO', 'TOCO'), ('TRUCK', 'TRUCK'), ('CAVALO_MECANICO', 'CAVALO_MECANICO'), ('CARRETA', 'CARRETA'), ('BITREM', 'BITREM'), ('RODOTREM', 'RODOTREM')], max_length=30),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['organization', 'operational_status'], name='vehicles_ve_organiz_1db703_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['body_type'], name='vehicles_ve_body_ty_fe2974_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['cargo_profile'], name='vehicles_ve_cargo_p_c18c9c_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['state'], name='vehicles_ve_state_2def9d_idx'),
        ),
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.UniqueConstraint(condition=models.Q(('renavam', ''), _negated=True), fields=('organization', 'renavam'), name='unique_vehicle_renavam_per_organization_when_present'),
        ),
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.UniqueConstraint(condition=models.Q(('chassis', ''), _negated=True), fields=('organization', 'chassis'), name='unique_vehicle_chassis_per_organization_when_present'),
        ),
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.CheckConstraint(condition=models.Q(('gross_weight_kg__gte', 0), ('gross_weight_kg', None), _connector='OR'), name='vehicle_gross_weight_non_negative'),
        ),
        migrations.AddField(
            model_name='refrigerationprofile',
            name='vehicle',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='refrigeration_profile', to='vehicles.vehicle'),
        ),
        migrations.AddField(
            model_name='vehicledocument',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='vehicles.vehicle'),
        ),
        migrations.AddField(
            model_name='vehicledocument',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_vehicle_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='refrigerationprofile',
            index=models.Index(fields=['next_maintenance_date'], name='vehicles_re_next_ma_ca26b2_idx'),
        ),
        migrations.AddIndex(
            model_name='refrigerationprofile',
            index=models.Index(fields=['control_type'], name='vehicles_re_control_24eb8b_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicledocument',
            index=models.Index(fields=['vehicle', 'status'], name='vehicles_ve_vehicle_b82afe_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicledocument',
            index=models.Index(fields=['document_type', 'status'], name='vehicles_ve_documen_c79bb0_idx'),
        ),
    ]
