# Generated by Django 5.2.17 on 2026-08-15 17:02

import django.db.models.deletion
import src.compliance.domain.enums
from django.conf import settings
from django.db import migrations, models


def migrate_verified_to_approved(apps, schema_editor):
    VehicleDocument = apps.get_model("vehicles", "VehicleDocument")
    VehicleDocument.objects.filter(status="VERIFIED").update(status="APPROVED")


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0002_refrigerationprofile_vehicledocument_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="vehicledocument",
            old_name="verified_at",
            new_name="reviewed_at",
        ),
        migrations.RenameField(
            model_name="vehicledocument",
            old_name="verified_by",
            new_name="reviewed_by",
        ),
        migrations.AddField(
            model_name="vehicledocument",
            name="content_hash",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="vehicledocument",
            name="issue_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vehicledocument",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="vehicledocument",
            name="original_filename",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="vehicledocument",
            name="rejection_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="vehicledocument",
            name="replaced_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="replaces",
                to="vehicles.vehicledocument",
            ),
        ),
        migrations.AlterField(
            model_name="vehicledocument",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_vehicle_documents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(migrate_verified_to_approved, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="vehicledocument",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "PENDING"),
                    ("UNDER_REVIEW", "UNDER_REVIEW"),
                    ("APPROVED", "APPROVED"),
                    ("REJECTED", "REJECTED"),
                    ("EXPIRED", "EXPIRED"),
                    ("REPLACED", "REPLACED"),
                ],
                default=src.compliance.domain.enums.DocumentStatus["PENDING"],
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="vehicledocument",
            index=models.Index(fields=["expiration_date"], name="vehicles_ve_expirat_56e549_idx"),
        ),
        migrations.AddConstraint(
            model_name="vehicledocument",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["PENDING", "UNDER_REVIEW", "APPROVED"])),
                fields=("vehicle", "document_type"),
                name="unique_active_vehicle_document_type",
            ),
        ),
    ]
