# Generated by Django 5.2.17 on 2026-08-15 15:18

import django.db.models.deletion
import src.carriers.domain.enums
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarrierProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trade_name', models.CharField(blank=True, max_length=180)),
                ('state_registration', models.CharField(blank=True, max_length=40)),
                ('municipal_registration', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('mobile_phone', models.CharField(blank=True, max_length=40)),
                ('site', models.CharField(blank=True, max_length=200)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('street', models.CharField(blank=True, max_length=180)),
                ('number', models.CharField(blank=True, max_length=20)),
                ('complement', models.CharField(blank=True, max_length=180)),
                ('district', models.CharField(blank=True, max_length=80)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('state', models.CharField(blank=True, max_length=2)),
                ('country', models.CharField(blank=True, default='BR', max_length=2)),
                ('rntrc', models.CharField(blank=True, max_length=40)),
                ('rntrc_category', models.CharField(blank=True, max_length=40)),
                ('rntrc_expiration', models.DateField(blank=True, null=True)),
                ('rntrc_status', models.CharField(blank=True, max_length=40)),
                ('cargo_profile', models.CharField(choices=[('DRY_CARGO', 'DRY_CARGO'), ('REFRIGERATED_CARGO', 'REFRIGERATED_CARGO'), ('BOTH', 'BOTH')], default=src.carriers.domain.enums.CarrierCargoProfile['DRY_CARGO'], max_length=20)),
                ('status', models.CharField(choices=[('PROSPECT', 'PROSPECT'), ('PENDING_APPROVAL', 'PENDING_APPROVAL'), ('ACTIVE', 'ACTIVE'), ('SUSPENDED', 'SUSPENDED'), ('BLOCKED', 'BLOCKED'), ('INACTIVE', 'INACTIVE')], default=src.carriers.domain.enums.CarrierStatus['PROSPECT'], max_length=20)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carrier_profiles', to='organizations.organization')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_carriers', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registered_carriers', to='organizations.organization')),
            ],
            options={
                'ordering': ['trade_name', 'organization__name'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='carriers_ca_tenant__bfe744_idx'), models.Index(fields=['owner'], name='carriers_ca_owner_i_9edbc6_idx'), models.Index(fields=['created_at'], name='carriers_ca_created_f67787_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'organization'), name='unique_tenant_carrier')],
            },
        ),
    ]
