# Generated by Django 5.2.17 on 2026-08-15 15:26

import django.db.models.deletion
import src.carriers.domain.enums
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carriers', '0001_initial'),
        ('drivers', '0001_initial'),
        ('organizations', '0001_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarrierDriverLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['carrier__trade_name', 'driver__full_name'],
            },
        ),
        migrations.CreateModel(
            name='CarrierVehicleLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('link_type', models.CharField(choices=[('OWNED', 'OWNED'), ('AGGREGATED', 'AGGREGATED'), ('THIRD_PARTY', 'THIRD_PARTY'), ('SUBCONTRACTED', 'SUBCONTRACTED')], default=src.carriers.domain.enums.CarrierVehicleLinkType['OWNED'], max_length=20)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['carrier__trade_name', 'vehicle__plate'],
            },
        ),
        migrations.AddIndex(
            model_name='carrierprofile',
            index=models.Index(fields=['tenant', 'cargo_profile'], name='carriers_ca_tenant__89cd13_idx'),
        ),
        migrations.AddIndex(
            model_name='carrierprofile',
            index=models.Index(fields=['tenant', 'rntrc'], name='carriers_ca_tenant__dccaa4_idx'),
        ),
        migrations.AddConstraint(
            model_name='carrierprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('rntrc', ''), _negated=True), fields=('tenant', 'rntrc'), name='unique_carrier_rntrc_per_tenant_when_present'),
        ),
        migrations.AddField(
            model_name='carrierdriverlink',
            name='carrier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_links', to='carriers.carrierprofile'),
        ),
        migrations.AddField(
            model_name='carrierdriverlink',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carrier_links', to='drivers.driver'),
        ),
        migrations.AddField(
            model_name='carriervehiclelink',
            name='carrier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_links', to='carriers.carrierprofile'),
        ),
        migrations.AddField(
            model_name='carriervehiclelink',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carrier_links', to='vehicles.vehicle'),
        ),
        migrations.AddIndex(
            model_name='carrierdriverlink',
            index=models.Index(fields=['carrier', 'active'], name='carriers_ca_carrier_844a51_idx'),
        ),
        migrations.AddIndex(
            model_name='carrierdriverlink',
            index=models.Index(fields=['driver', 'active'], name='carriers_ca_driver__72b8bd_idx'),
        ),
        migrations.AddConstraint(
            model_name='carrierdriverlink',
            constraint=models.UniqueConstraint(fields=('carrier', 'driver'), name='unique_driver_link_per_carrier'),
        ),
        migrations.AddIndex(
            model_name='carriervehiclelink',
            index=models.Index(fields=['carrier', 'active'], name='carriers_ca_carrier_c234d1_idx'),
        ),
        migrations.AddIndex(
            model_name='carriervehiclelink',
            index=models.Index(fields=['vehicle', 'active'], name='carriers_ca_vehicle_0ddf51_idx'),
        ),
        migrations.AddIndex(
            model_name='carriervehiclelink',
            index=models.Index(fields=['link_type'], name='carriers_ca_link_ty_14d95a_idx'),
        ),
        migrations.AddConstraint(
            model_name='carriervehiclelink',
            constraint=models.UniqueConstraint(fields=('carrier', 'vehicle'), name='unique_vehicle_link_per_carrier'),
        ),
    ]
