# Generated by Django 5.2.17 on 2026-08-15 17:02

import django.db.models.deletion
import src.compliance.domain.enums
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carriers', '0002_carrierdriverlink_carriervehiclelink_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarrierDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('CNPJ_CARD', 'CNPJ_CARD'), ('RNTRC_ANTT', 'RNTRC_ANTT'), ('CONTRACT', 'CONTRACT'), ('INSURANCE_POLICY', 'INSURANCE_POLICY'), ('CORPORATE_DOCUMENT', 'CORPORATE_DOCUMENT'), ('CERTIFICATE', 'CERTIFICATE'), ('OTHER', 'OTHER')], max_length=40)),
                ('storage_key', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('UNDER_REVIEW', 'UNDER_REVIEW'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED'), ('EXPIRED', 'EXPIRED'), ('REPLACED', 'REPLACED')], default=src.compliance.domain.enums.DocumentStatus['PENDING'], max_length=20)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('content_hash', models.CharField(blank=True, max_length=64)),
                ('notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='carriers.carrierprofile')),
                ('replaced_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaces', to='carriers.carrierdocument')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_carrier_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['carrier__trade_name', 'document_type', '-created_at'],
                'indexes': [models.Index(fields=['carrier', 'status'], name='carriers_ca_carrier_33236d_idx'), models.Index(fields=['document_type', 'status'], name='carriers_ca_documen_006c44_idx'), models.Index(fields=['expiration_date'], name='carriers_ca_expirat_470eb7_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['PENDING', 'UNDER_REVIEW', 'APPROVED'])), fields=('carrier', 'document_type'), name='unique_active_carrier_document_type')],
            },
        ),
    ]
