# Generated by Django 5.2.17 on 2026-08-15 17:43

import django.db.models.deletion
import src.freights.domain.enums
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_seed_customer_permissions'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FreightRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference_code', models.CharField(blank=True, max_length=32)),
                ('status', models.CharField(choices=[('DRAFT', 'DRAFT'), ('SUBMITTED', 'SUBMITTED'), ('UNDER_REVIEW', 'UNDER_REVIEW'), ('QUOTING', 'QUOTING'), ('READY_TO_PUBLISH', 'READY_TO_PUBLISH'), ('CANCELLED', 'CANCELLED'), ('CLOSED', 'CLOSED')], default=src.freights.domain.enums.FreightRequestStatus['DRAFT'], max_length=30)),
                ('priority', models.CharField(choices=[('NORMAL', 'NORMAL'), ('URGENT', 'URGENT'), ('SCHEDULED', 'SCHEDULED')], default=src.freights.domain.enums.FreightRequestPriority['NORMAL'], max_length=20)),
                ('instructions', models.TextField(blank=True)),
                ('handling_requirements', models.TextField(blank=True)),
                ('hazardous_material', models.BooleanField(default=False)),
                ('declared_cargo_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('currency', models.CharField(blank=True, default='BRL', max_length=3)),
                ('vehicle_type_required', models.CharField(blank=True, choices=[('MOTORCYCLE', 'MOTORCYCLE'), ('CAR', 'CAR'), ('UTILITY', 'UTILITY'), ('PICKUP', 'PICKUP'), ('SEMI_TRUCK', 'SEMI_TRUCK'), ('TRAILER', 'TRAILER'), ('MOTO', 'MOTO'), ('CARRO', 'CARRO'), ('UTILITARIO', 'UTILITARIO'), ('VAN', 'VAN'), ('VUC', 'VUC'), ('TOCO', 'TOCO'), ('TRUCK', 'TRUCK'), ('CAVALO_MECANICO', 'CAVALO_MECANICO'), ('CARRETA', 'CARRETA'), ('BITREM', 'BITREM'), ('RODOTREM', 'RODOTREM')], max_length=30)),
                ('body_type_required', models.CharField(blank=True, choices=[('BAU', 'BAU'), ('BAU_REFRIGERADO', 'BAU_REFRIGERADO'), ('SIDER', 'SIDER'), ('GRADE_BAIXA', 'GRADE_BAIXA'), ('GRANELEIRO', 'GRANELEIRO'), ('CACAMBA', 'CACAMBA'), ('PLATAFORMA', 'PLATAFORMA'), ('TANQUE', 'TANQUE'), ('CEGONHA', 'CEGONHA')], max_length=30)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_freight_requests', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_freight_requests', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='freight_requests', to='customers.customer')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='freight_requests', to='organizations.organization')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_freight_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FreightRequestCargo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True)),
                ('cargo_type', models.CharField(choices=[('GENERAL_CARGO', 'GENERAL_CARGO'), ('FOOD', 'FOOD'), ('BEVERAGE', 'BEVERAGE'), ('PHARMACEUTICAL', 'PHARMACEUTICAL'), ('ELECTRONICS', 'ELECTRONICS'), ('MACHINERY', 'MACHINERY'), ('CONSTRUCTION_MATERIAL', 'CONSTRUCTION_MATERIAL'), ('OTHER', 'OTHER')], default=src.freights.domain.enums.FreightCargoType['GENERAL_CARGO'], max_length=40)),
                ('cargo_profile', models.CharField(choices=[('DRY_CARGO', 'DRY_CARGO'), ('REFRIGERATED_CARGO', 'REFRIGERATED_CARGO')], default=src.freights.domain.enums.FreightCargoProfile['DRY_CARGO'], max_length=30)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('volume_m3', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('package_count', models.PositiveIntegerField(blank=True, null=True)),
                ('package_type', models.CharField(blank=True, max_length=80)),
                ('temperature_min_c', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('temperature_max_c', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('target_temperature_c', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('freight_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cargo', to='freights.freightrequest')),
            ],
        ),
        migrations.CreateModel(
            name='FreightRequestReferenceSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('last_value', models.PositiveIntegerField(default=0)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freight_request_sequences', to='organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='FreightRequestStop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.PositiveSmallIntegerField(default=1)),
                ('stop_type', models.CharField(choices=[('PICKUP', 'PICKUP'), ('DELIVERY', 'DELIVERY')], max_length=20)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('street', models.CharField(blank=True, max_length=180)),
                ('number', models.CharField(blank=True, max_length=20)),
                ('complement', models.CharField(blank=True, max_length=180)),
                ('district', models.CharField(blank=True, max_length=80)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('state', models.CharField(blank=True, max_length=2)),
                ('country', models.CharField(blank=True, default='BR', max_length=2)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('instructions', models.TextField(blank=True)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('window_start', models.TimeField(blank=True, null=True)),
                ('window_end', models.TimeField(blank=True, null=True)),
                ('freight_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='freights.freightrequest')),
            ],
            options={
                'ordering': ['sequence', 'stop_type'],
            },
        ),
        migrations.AddIndex(
            model_name='freightrequest',
            index=models.Index(fields=['organization', 'status'], name='freights_fr_organiz_da2672_idx'),
        ),
        migrations.AddIndex(
            model_name='freightrequest',
            index=models.Index(fields=['organization', 'customer'], name='freights_fr_organiz_121ee4_idx'),
        ),
        migrations.AddIndex(
            model_name='freightrequest',
            index=models.Index(fields=['owner'], name='freights_fr_owner_i_f9d108_idx'),
        ),
        migrations.AddIndex(
            model_name='freightrequest',
            index=models.Index(fields=['reference_code'], name='freights_fr_referen_dc3d27_idx'),
        ),
        migrations.AddIndex(
            model_name='freightrequest',
            index=models.Index(fields=['created_at'], name='freights_fr_created_443630_idx'),
        ),
        migrations.AddConstraint(
            model_name='freightrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('reference_code', ''), _negated=True), fields=('organization', 'reference_code'), name='unique_freight_request_reference_per_organization'),
        ),
        migrations.AddIndex(
            model_name='freightrequestcargo',
            index=models.Index(fields=['cargo_profile'], name='freights_fr_cargo_p_d4f54c_idx'),
        ),
        migrations.AddIndex(
            model_name='freightrequestcargo',
            index=models.Index(fields=['cargo_type'], name='freights_fr_cargo_t_d75874_idx'),
        ),
        migrations.AddConstraint(
            model_name='freightrequestreferencesequence',
            constraint=models.UniqueConstraint(fields=('organization', 'year'), name='unique_freight_request_sequence_per_org_year'),
        ),
        migrations.AddIndex(
            model_name='freightrequeststop',
            index=models.Index(fields=['freight_request', 'stop_type'], name='freights_fr_freight_e5a25d_idx'),
        ),
        migrations.AddIndex(
            model_name='freightrequeststop',
            index=models.Index(fields=['freight_request', 'sequence'], name='freights_fr_freight_36eac5_idx'),
        ),
        migrations.AddIndex(
            model_name='freightrequeststop',
            index=models.Index(fields=['state'], name='freights_fr_state_98798f_idx'),
        ),
        migrations.AddIndex(
            model_name='freightrequeststop',
            index=models.Index(fields=['city'], name='freights_fr_city_45d04b_idx'),
        ),
        migrations.AddConstraint(
            model_name='freightrequeststop',
            constraint=models.UniqueConstraint(fields=('freight_request', 'sequence'), name='unique_freight_request_stop_sequence'),
        ),
    ]
