# Generated by Django 5.2.17 on 2026-08-15 17:54

import django.db.models.deletion
import src.freights.domain.quote_enums
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freights', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FreightQuote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference_code', models.CharField(blank=True, max_length=32)),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('DRAFT', 'DRAFT'), ('CALCULATED', 'CALCULATED'), ('UNDER_REVIEW', 'UNDER_REVIEW'), ('APPROVED', 'APPROVED'), ('SENT', 'SENT'), ('ACCEPTED', 'ACCEPTED'), ('REJECTED', 'REJECTED'), ('EXPIRED', 'EXPIRED'), ('CANCELLED', 'CANCELLED'), ('SUPERSEDED', 'SUPERSEDED')], default=src.freights.domain.quote_enums.FreightQuoteStatus['DRAFT'], max_length=30)),
                ('pricing_method', models.CharField(choices=[('MANUAL', 'MANUAL'), ('RULE_BASED', 'RULE_BASED'), ('AUTOMATED', 'AUTOMATED'), ('NEGOTIATED', 'NEGOTIATED')], default=src.freights.domain.quote_enums.FreightPricingMethod['MANUAL'], max_length=20)),
                ('currency', models.CharField(blank=True, default='BRL', max_length=3)),
                ('base_freight_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('additional_charges', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('insurance_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('customer_price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('estimated_distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estimated_duration_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('premises_snapshot', models.JSONField(blank=True, default=dict)),
                ('internal_notes', models.TextField(blank=True)),
                ('customer_notes', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('submitted_for_review_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_freight_quotes', to=settings.AUTH_USER_MODEL)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_freight_quotes', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_freight_quotes', to=settings.AUTH_USER_MODEL)),
                ('freight_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to='freights.freightrequest')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='freight_quotes', to='organizations.organization')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_freight_quotes', to=settings.AUTH_USER_MODEL)),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_freight_quotes', to=settings.AUTH_USER_MODEL)),
                ('revision_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisions', to='freights.freightquote')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_freight_quotes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FreightQuoteCharge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('charge_type', models.CharField(choices=[('BASE_FREIGHT', 'BASE_FREIGHT'), ('TOLL', 'TOLL'), ('REFRIGERATION_SURCHARGE', 'REFRIGERATION_SURCHARGE'), ('INSURANCE', 'INSURANCE'), ('LOADING_UNLOADING', 'LOADING_UNLOADING'), ('DAILY_RATE', 'DAILY_RATE'), ('DEMURRAGE', 'DEMURRAGE'), ('ADMIN_FEE', 'ADMIN_FEE'), ('DISCOUNT', 'DISCOUNT'), ('OTHER', 'OTHER')], default=src.freights.domain.quote_enums.FreightQuoteChargeType['OTHER'], max_length=40)),
                ('description', models.CharField(blank=True, max_length=180)),
                ('quantity', models.DecimalField(decimal_places=3, default=1, max_digits=12)),
                ('unit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('is_discount', models.BooleanField(default=False)),
                ('sequence', models.PositiveSmallIntegerField(default=1)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='freights.freightquote')),
            ],
            options={
                'ordering': ['sequence', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='FreightQuoteReferenceSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('last_value', models.PositiveIntegerField(default=0)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freight_quote_sequences', to='organizations.organization')),
            ],
        ),
        migrations.AddIndex(
            model_name='freightquote',
            index=models.Index(fields=['organization', 'status'], name='freights_fr_organiz_2fc4f1_idx'),
        ),
        migrations.AddIndex(
            model_name='freightquote',
            index=models.Index(fields=['freight_request', 'version'], name='freights_fr_freight_1bb5bd_idx'),
        ),
        migrations.AddIndex(
            model_name='freightquote',
            index=models.Index(fields=['owner'], name='freights_fr_owner_i_efdca8_idx'),
        ),
        migrations.AddIndex(
            model_name='freightquote',
            index=models.Index(fields=['reference_code'], name='freights_fr_referen_595a82_idx'),
        ),
        migrations.AddIndex(
            model_name='freightquote',
            index=models.Index(fields=['valid_until'], name='freights_fr_valid_u_cbd7ef_idx'),
        ),
        migrations.AddIndex(
            model_name='freightquote',
            index=models.Index(fields=['created_at'], name='freights_fr_created_d27262_idx'),
        ),
        migrations.AddConstraint(
            model_name='freightquote',
            constraint=models.UniqueConstraint(condition=models.Q(('reference_code', ''), _negated=True), fields=('organization', 'reference_code'), name='unique_freight_quote_reference_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='freightquote',
            constraint=models.UniqueConstraint(fields=('freight_request', 'version'), name='unique_freight_quote_version_per_request'),
        ),
        migrations.AddIndex(
            model_name='freightquotecharge',
            index=models.Index(fields=['quote', 'sequence'], name='freights_fr_quote_i_6ff51a_idx'),
        ),
        migrations.AddIndex(
            model_name='freightquotecharge',
            index=models.Index(fields=['charge_type'], name='freights_fr_charge__c00999_idx'),
        ),
        migrations.AddConstraint(
            model_name='freightquotereferencesequence',
            constraint=models.UniqueConstraint(fields=('organization', 'year'), name='unique_freight_quote_sequence_per_org_year'),
        ),
    ]
