# Generated by Django 5.2.17 on 2026-08-15 18:05

import django.db.models.deletion
import src.freights.domain.offer_enums
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carriers', '0003_carrierdocument'),
        ('drivers', '0003_remove_driverdocument_unique_active_driver_document_type_and_more'),
        ('freights', '0002_freightquote_freightquotecharge_and_more'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FreightOffer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference_code', models.CharField(blank=True, max_length=32)),
                ('status', models.CharField(choices=[('DRAFT', 'DRAFT'), ('READY', 'READY'), ('PUBLISHED', 'PUBLISHED'), ('PAUSED', 'PAUSED'), ('EXPIRED', 'EXPIRED'), ('CANCELLED', 'CANCELLED'), ('CLOSED', 'CLOSED')], default=src.freights.domain.offer_enums.FreightOfferStatus['DRAFT'], max_length=30)),
                ('offer_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('currency', models.CharField(blank=True, default='BRL', max_length=3)),
                ('audience', models.CharField(choices=[('CARRIERS', 'CARRIERS'), ('DRIVERS', 'DRIVERS'), ('BOTH', 'BOTH'), ('PRIVATE', 'PRIVATE')], default=src.freights.domain.offer_enums.FreightOfferAudience['CARRIERS'], max_length=20)),
                ('premises_snapshot', models.JSONField(blank=True, default=dict)),
                ('internal_notes', models.TextField(blank=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('ready_at', models.DateTimeField(blank=True, null=True)),
                ('paused_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_freight_offers', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_freight_offers', to=settings.AUTH_USER_MODEL)),
                ('freight_quote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offers', to='freights.freightquote')),
                ('freight_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offers', to='freights.freightrequest')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='freight_offers', to='organizations.organization')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_freight_offers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FreightOfferReferenceSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('last_value', models.PositiveIntegerField(default=0)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freight_offer_sequences', to='organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='FreightOfferTarget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('carrier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='freight_offer_targets', to='carriers.carrierprofile')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='freight_offer_targets', to='drivers.driver')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='freights.freightoffer')),
            ],
        ),
        migrations.AddIndex(
            model_name='freightoffer',
            index=models.Index(fields=['organization', 'status'], name='freights_fr_organiz_333564_idx'),
        ),
        migrations.AddIndex(
            model_name='freightoffer',
            index=models.Index(fields=['freight_request', 'status'], name='freights_fr_freight_17b834_idx'),
        ),
        migrations.AddIndex(
            model_name='freightoffer',
            index=models.Index(fields=['organization', 'audience', 'status'], name='freights_fr_organiz_f736ff_idx'),
        ),
        migrations.AddIndex(
            model_name='freightoffer',
            index=models.Index(fields=['expires_at'], name='freights_fr_expires_a5fd8f_idx'),
        ),
        migrations.AddConstraint(
            model_name='freightofferreferencesequence',
            constraint=models.UniqueConstraint(fields=('organization', 'year'), name='unique_freight_offer_sequence_per_org_year'),
        ),
        migrations.AddConstraint(
            model_name='freightoffertarget',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('carrier__isnull', False), ('driver__isnull', True)), models.Q(('carrier__isnull', True), ('driver__isnull', False)), _connector='OR'), name='freight_offer_target_exactly_one_entity'),
        ),
        migrations.AddConstraint(
            model_name='freightoffertarget',
            constraint=models.UniqueConstraint(condition=models.Q(('carrier__isnull', False)), fields=('offer', 'carrier'), name='unique_freight_offer_carrier_target'),
        ),
        migrations.AddConstraint(
            model_name='freightoffertarget',
            constraint=models.UniqueConstraint(condition=models.Q(('driver__isnull', False)), fields=('offer', 'driver'), name='unique_freight_offer_driver_target'),
        ),
    ]
