# Generated by Django 5.2.17 on 2026-08-15 18:23

import django.db.models.deletion
import src.freights.domain.matching_enums
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carriers', '0003_carrierdocument'),
        ('drivers', '0003_remove_driverdocument_unique_active_driver_document_type_and_more'),
        ('freights', '0003_freightoffer_freightofferreferencesequence_and_more'),
        ('organizations', '0001_initial'),
        ('vehicles', '0003_rename_verified_at_vehicledocument_reviewed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FreightMatchGeneration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('algorithm_version', models.CharField(max_length=20)),
                ('generation_number', models.PositiveIntegerField()),
                ('is_current', models.BooleanField(default=True)),
                ('candidate_count', models.PositiveIntegerField(default=0)),
                ('eligible_count', models.PositiveIntegerField(default=0)),
                ('ineligible_count', models.PositiveIntegerField(default=0)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_freight_match_generations', to=settings.AUTH_USER_MODEL)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_generations', to='freights.freightoffer')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='freight_match_generations', to='organizations.organization')),
            ],
            options={
                'ordering': ['-generation_number'],
            },
        ),
        migrations.CreateModel(
            name='FreightMatchCandidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('eligibility_status', models.CharField(choices=[('ELIGIBLE', 'ELIGIBLE'), ('INELIGIBLE', 'INELIGIBLE'), ('UNKNOWN', 'UNKNOWN')], default=src.freights.domain.matching_enums.MatchEligibilityStatus['UNKNOWN'], max_length=20)),
                ('eligibility_reasons', models.JSONField(blank=True, default=list)),
                ('distance_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('compliance_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('vehicle_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cargo_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('temperature_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('availability_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('performance_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('price_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('total_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('rank_position', models.PositiveIntegerField(blank=True, null=True)),
                ('distance_to_pickup_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estimated_deadhead_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('algorithm_version', models.CharField(max_length=20)),
                ('score_explanation', models.JSONField(blank=True, default=dict)),
                ('generated_at', models.DateTimeField()),
                ('carrier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_candidates', to='carriers.carrierprofile')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_candidates', to='drivers.driver')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_candidates', to='freights.freightoffer')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='freight_match_candidates', to='organizations.organization')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_candidates', to='vehicles.vehicle')),
                ('generation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='freights.freightmatchgeneration')),
            ],
            options={
                'ordering': ['rank_position', '-total_score'],
            },
        ),
        migrations.CreateModel(
            name='FreightOfferInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('SENT', 'SENT'), ('VIEWED', 'VIEWED'), ('DECLINED', 'DECLINED'), ('EXPIRED', 'EXPIRED'), ('CANCELLED', 'CANCELLED')], default=src.freights.domain.matching_enums.FreightOfferInvitationStatus['PENDING'], max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('viewed_at', models.DateTimeField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('decline_reason', models.CharField(blank=True, choices=[('PRICE_TOO_LOW', 'PRICE_TOO_LOW'), ('TOO_FAR', 'TOO_FAR'), ('VEHICLE_UNAVAILABLE', 'VEHICLE_UNAVAILABLE'), ('DRIVER_UNAVAILABLE', 'DRIVER_UNAVAILABLE'), ('ROUTE_NOT_INTERESTING', 'ROUTE_NOT_INTERESTING'), ('TIME_WINDOW', 'TIME_WINDOW'), ('CARGO_TYPE', 'CARGO_TYPE'), ('TEMPERATURE_REQUIREMENT', 'TEMPERATURE_REQUIREMENT'), ('RETURN_LOAD_REQUIRED', 'RETURN_LOAD_REQUIRED'), ('OTHER', 'OTHER')], max_length=40)),
                ('decline_notes', models.TextField(blank=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_freight_offer_invitations', to=settings.AUTH_USER_MODEL)),
                ('carrier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='freight_offer_invitations', to='carriers.carrierprofile')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_freight_offer_invitations', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='freight_offer_invitations', to='drivers.driver')),
                ('match_candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitations', to='freights.freightmatchcandidate')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='freights.freightoffer')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='freight_offer_invitations', to='organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='MarketplaceEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('offer_published', 'offer_published'), ('offer_impression', 'offer_impression'), ('offer_opened', 'offer_opened'), ('offer_invited', 'offer_invited'), ('offer_invitation_viewed', 'offer_invitation_viewed'), ('offer_declined', 'offer_declined')], max_length=40)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketplace_events', to=settings.AUTH_USER_MODEL)),
                ('carrier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketplace_events', to='carriers.carrierprofile')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketplace_events', to='drivers.driver')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_events', to='freights.freightoffer')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marketplace_events', to='organizations.organization')),
            ],
        ),
        migrations.AddIndex(
            model_name='freightmatchgeneration',
            index=models.Index(fields=['offer', 'is_current'], name='freights_fr_offer_i_d33333_idx'),
        ),
        migrations.AddIndex(
            model_name='freightmatchgeneration',
            index=models.Index(fields=['organization', 'algorithm_version'], name='freights_fr_organiz_3dddaa_idx'),
        ),
        migrations.AddConstraint(
            model_name='freightmatchgeneration',
            constraint=models.UniqueConstraint(fields=('offer', 'generation_number'), name='unique_freight_match_generation_per_offer'),
        ),
        migrations.AddConstraint(
            model_name='freightmatchgeneration',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('offer',), name='unique_current_freight_match_generation_per_offer'),
        ),
        migrations.AddIndex(
            model_name='freightmatchcandidate',
            index=models.Index(fields=['offer', 'eligibility_status'], name='freights_fr_offer_i_da504d_idx'),
        ),
        migrations.AddIndex(
            model_name='freightmatchcandidate',
            index=models.Index(fields=['generation', 'rank_position'], name='freights_fr_generat_85019b_idx'),
        ),
        migrations.AddIndex(
            model_name='freightmatchcandidate',
            index=models.Index(fields=['organization', 'total_score'], name='freights_fr_organiz_f82684_idx'),
        ),
        migrations.AddIndex(
            model_name='freightmatchcandidate',
            index=models.Index(fields=['algorithm_version'], name='freights_fr_algorit_8b0a3c_idx'),
        ),
        migrations.AddConstraint(
            model_name='freightmatchcandidate',
            constraint=models.UniqueConstraint(condition=models.Q(('rank_position__isnull', False)), fields=('generation', 'rank_position'), name='unique_rank_per_match_generation'),
        ),
        migrations.AddIndex(
            model_name='freightofferinvitation',
            index=models.Index(fields=['offer', 'status'], name='freights_fr_offer_i_2bfd57_idx'),
        ),
        migrations.AddIndex(
            model_name='freightofferinvitation',
            index=models.Index(fields=['organization', 'status'], name='freights_fr_organiz_242cb5_idx'),
        ),
        migrations.AddIndex(
            model_name='freightofferinvitation',
            index=models.Index(fields=['match_candidate', 'status'], name='freights_fr_match_c_282f01_idx'),
        ),
        migrations.AddConstraint(
            model_name='freightofferinvitation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('carrier__isnull', False), ('driver__isnull', True)), models.Q(('carrier__isnull', True), ('driver__isnull', False)), _connector='OR'), name='freight_offer_invitation_single_entity'),
        ),
        migrations.AddIndex(
            model_name='marketplaceevent',
            index=models.Index(fields=['organization', 'event_type'], name='freights_ma_organiz_a60a28_idx'),
        ),
        migrations.AddIndex(
            model_name='marketplaceevent',
            index=models.Index(fields=['offer', 'event_type'], name='freights_ma_offer_i_f5cc88_idx'),
        ),
        migrations.AddIndex(
            model_name='marketplaceevent',
            index=models.Index(fields=['created_at'], name='freights_ma_created_2484f4_idx'),
        ),
    ]
