# Generated by Django 5.2.17 on 2026-08-15 20:29

import django.db.models.deletion
import src.freights.domain.matching_enums
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carriers', '0003_carrierdocument'),
        ('drivers', '0004_driver_route_intent'),
        ('freights', '0004_freight_matching_intelligence'),
        ('organizations', '0001_initial'),
        ('vehicles', '0003_rename_verified_at_vehicledocument_reviewed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketplaceevent',
            name='event_type',
            field=models.CharField(choices=[('offer_published', 'offer_published'), ('offer_impression', 'offer_impression'), ('offer_opened', 'offer_opened'), ('offer_invited', 'offer_invited'), ('offer_invitation_viewed', 'offer_invitation_viewed'), ('offer_declined', 'offer_declined'), ('offer_interest_expressed', 'offer_interest_expressed'), ('offer_interest_withdrawn', 'offer_interest_withdrawn'), ('offer_candidate_selected', 'offer_candidate_selected'), ('offer_selection_confirmed', 'offer_selection_confirmed'), ('offer_selection_declined', 'offer_selection_declined'), ('offer_selection_expired', 'offer_selection_expired')], max_length=40),
        ),
        migrations.CreateModel(
            name='FreightOfferInterest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('WITHDRAWN', 'WITHDRAWN'), ('NOT_SELECTED', 'NOT_SELECTED'), ('SELECTED', 'SELECTED'), ('EXPIRED', 'EXPIRED'), ('CANCELLED', 'CANCELLED')], default=src.freights.domain.matching_enums.FreightOfferInterestStatus['ACTIVE'], max_length=20)),
                ('expressed_at', models.DateTimeField()),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('carrier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='freight_offer_interests', to='carriers.carrierprofile')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='freight_offer_interests', to='drivers.driver')),
                ('invitation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interests', to='freights.freightofferinvitation')),
                ('match_candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interests', to='freights.freightmatchcandidate')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='freights.freightoffer')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='freight_offer_interests', to='organizations.organization')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='freight_offer_interests', to='vehicles.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='FreightOfferSelection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('selected_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('PENDING_CONFIRMATION', 'PENDING_CONFIRMATION'), ('CONFIRMED', 'CONFIRMED'), ('DECLINED', 'DECLINED'), ('EXPIRED', 'EXPIRED'), ('CANCELLED', 'CANCELLED')], default=src.freights.domain.matching_enums.FreightOfferSelectionStatus['PENDING_CONFIRMATION'], max_length=30)),
                ('confirmation_expires_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('declined_at', models.DateTimeField(blank=True, null=True)),
                ('declined_reason', models.CharField(blank=True, choices=[('VEHICLE_UNAVAILABLE', 'VEHICLE_UNAVAILABLE'), ('DRIVER_UNAVAILABLE', 'DRIVER_UNAVAILABLE'), ('SCHEDULE_CONFLICT', 'SCHEDULE_CONFLICT'), ('PRICE_NOT_ACCEPTED', 'PRICE_NOT_ACCEPTED'), ('ROUTE_CHANGED', 'ROUTE_CHANGED'), ('OPERATIONAL_ISSUE', 'OPERATIONAL_ISSUE'), ('OTHER', 'OTHER')], max_length=30, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.TextField(blank=True)),
                ('carrier_snapshot', models.JSONField(blank=True, null=True)),
                ('driver_snapshot', models.JSONField(blank=True, null=True)),
                ('vehicle_snapshot', models.JSONField(blank=True, null=True)),
                ('route_snapshot', models.JSONField(blank=True, null=True)),
                ('cargo_snapshot', models.JSONField(blank=True, null=True)),
                ('premises_snapshot', models.JSONField(blank=True, null=True)),
                ('match_score_snapshot', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('rank_snapshot', models.IntegerField(blank=True, null=True)),
                ('algorithm_version_snapshot', models.CharField(blank=True, max_length=20, null=True)),
                ('route_intent_bonus_snapshot', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('interest', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='selections', to='freights.freightofferinterest')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='freights.freightoffer')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='freight_offer_selections', to='organizations.organization')),
                ('selected_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='selections_made', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='freightofferinterest',
            index=models.Index(fields=['offer', 'status'], name='freights_fr_offer_i_22916f_idx'),
        ),
        migrations.AddIndex(
            model_name='freightofferinterest',
            index=models.Index(fields=['organization', 'status'], name='freights_fr_organiz_bcf80f_idx'),
        ),
        migrations.AddConstraint(
            model_name='freightofferinterest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('offer', 'carrier', 'driver', 'vehicle'), name='unique_active_interest_per_candidate_combination'),
        ),
        migrations.AddIndex(
            model_name='freightofferselection',
            index=models.Index(fields=['offer', 'status'], name='freights_fr_offer_i_2b00a2_idx'),
        ),
        migrations.AddIndex(
            model_name='freightofferselection',
            index=models.Index(fields=['organization', 'status'], name='freights_fr_organiz_64803b_idx'),
        ),
        migrations.AddConstraint(
            model_name='freightofferselection',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['PENDING_CONFIRMATION', 'CONFIRMED'])), fields=('offer',), name='unique_active_selection_per_offer'),
        ),
    ]
