# Generated by Django 5.2.17 on 2026-08-15 23:29

import django.db.models.deletion
import src.freights.domain.enums
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carriers', '0003_carrierdocument'),
        ('drivers', '0004_driver_route_intent'),
        ('freights', '0005_alter_marketplaceevent_event_type_and_more'),
        ('organizations', '0001_initial'),
        ('vehicles', '0003_rename_verified_at_vehicledocument_reviewed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FreightOperation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('ASSIGNED', 'ASSIGNED'), ('DRIVER_EN_ROUTE_TO_PICKUP', 'DRIVER_EN_ROUTE_TO_PICKUP'), ('ARRIVED_AT_PICKUP', 'ARRIVED_AT_PICKUP'), ('LOADING', 'LOADING'), ('IN_TRANSIT', 'IN_TRANSIT'), ('ARRIVED_AT_DELIVERY', 'ARRIVED_AT_DELIVERY'), ('UNLOADING', 'UNLOADING'), ('DELIVERED', 'DELIVERED'), ('CANCELLED', 'CANCELLED')], default=src.freights.domain.enums.OperationStatus['ASSIGNED'], max_length=30)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('request_snapshot', models.JSONField(blank=True, null=True)),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='carriers.carrierprofile')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='drivers.driver')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='freight_operations', to='organizations.organization')),
                ('selection', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='operation', to='freights.freightofferselection')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='vehicles.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='FreightOperationEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('OPERATION_CREATED', 'OPERATION_CREATED'), ('STATUS_CHANGED', 'STATUS_CHANGED'), ('INCIDENT_REPORTED', 'INCIDENT_REPORTED'), ('POD_CREATED', 'POD_CREATED'), ('CANCELLED', 'CANCELLED')], max_length=30)),
                ('previous_status', models.CharField(blank=True, choices=[('ASSIGNED', 'ASSIGNED'), ('DRIVER_EN_ROUTE_TO_PICKUP', 'DRIVER_EN_ROUTE_TO_PICKUP'), ('ARRIVED_AT_PICKUP', 'ARRIVED_AT_PICKUP'), ('LOADING', 'LOADING'), ('IN_TRANSIT', 'IN_TRANSIT'), ('ARRIVED_AT_DELIVERY', 'ARRIVED_AT_DELIVERY'), ('UNLOADING', 'UNLOADING'), ('DELIVERED', 'DELIVERED'), ('CANCELLED', 'CANCELLED')], max_length=30, null=True)),
                ('new_status', models.CharField(blank=True, choices=[('ASSIGNED', 'ASSIGNED'), ('DRIVER_EN_ROUTE_TO_PICKUP', 'DRIVER_EN_ROUTE_TO_PICKUP'), ('ARRIVED_AT_PICKUP', 'ARRIVED_AT_PICKUP'), ('LOADING', 'LOADING'), ('IN_TRANSIT', 'IN_TRANSIT'), ('ARRIVED_AT_DELIVERY', 'ARRIVED_AT_DELIVERY'), ('UNLOADING', 'UNLOADING'), ('DELIVERED', 'DELIVERED'), ('CANCELLED', 'CANCELLED')], max_length=30, null=True)),
                ('origin', models.CharField(choices=[('BACKOFFICE', 'BACKOFFICE'), ('MOBILE_APP', 'MOBILE_APP'), ('API', 'API'), ('SYSTEM', 'SYSTEM')], max_length=20)),
                ('occurred_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('notes', models.TextField(blank=True)),
                ('client_event_id', models.CharField(blank=True, max_length=255, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operation_events', to=settings.AUTH_USER_MODEL)),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='freights.freightoperation')),
            ],
        ),
        migrations.CreateModel(
            name='ProofOfDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receiver_name', models.CharField(blank=True, max_length=120)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('notes', models.TextField(blank=True)),
                ('operation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='pod', to='freights.freightoperation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='freightoperation',
            index=models.Index(fields=['organization', 'status'], name='freights_fr_organiz_d3bf3c_idx'),
        ),
        migrations.AddIndex(
            model_name='freightoperationevent',
            index=models.Index(fields=['operation', 'event_type'], name='freights_fr_operati_82c51c_idx'),
        ),
        migrations.AddIndex(
            model_name='freightoperationevent',
            index=models.Index(fields=['operation', 'client_event_id'], name='freights_fr_operati_9a3db2_idx'),
        ),
        migrations.AddConstraint(
            model_name='freightoperationevent',
            constraint=models.UniqueConstraint(condition=models.Q(('client_event_id__isnull', True), _negated=True), fields=('operation', 'client_event_id'), name='unique_event_per_operation'),
        ),
    ]
