# Generated by Django 6.1 on 2026-08-16 03:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0004_driver_route_intent'),
        ('freights', '0006_freightoperation_freightoperationevent_and_more'),
        ('organizations', '0001_initial'),
        ('vehicles', '0003_rename_verified_at_vehicledocument_reviewed_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('ENDED', 'ENDED'), ('CANCELLED', 'CANCELLED')], default='ACTIVE', max_length=30)),
                ('source', models.CharField(blank=True, max_length=50)),
                ('device_metadata', models.JSONField(blank=True, null=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tracking_sessions', to='drivers.driver')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tracking_sessions', to='freights.freightoperation')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tracking_sessions', to='organizations.organization')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tracking_sessions', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='LocationPoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('accuracy_m', models.DecimalField(decimal_places=2, max_digits=8)),
                ('speed_kph', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('heading_deg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('altitude_m', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('recorded_at', models.DateTimeField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('sequence', models.PositiveIntegerField(blank=True, null=True)),
                ('client_event_id', models.CharField(blank=True, max_length=255, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='location_points', to='drivers.driver')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='location_points', to='freights.freightoperation')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='location_points', to='organizations.organization')),
                ('tracking_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_points', to='freights.trackingsession')),
            ],
            options={
                'ordering': ['recorded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='trackingsession',
            index=models.Index(fields=['organization', 'status'], name='freights_tr_organiz_fc52ec_idx'),
        ),
        migrations.AddIndex(
            model_name='trackingsession',
            index=models.Index(fields=['operation', 'status'], name='freights_tr_operati_158abe_idx'),
        ),
        migrations.AddIndex(
            model_name='locationpoint',
            index=models.Index(fields=['operation', 'recorded_at'], name='freights_lo_operati_b951d6_idx'),
        ),
        migrations.AddIndex(
            model_name='locationpoint',
            index=models.Index(fields=['tracking_session', 'recorded_at'], name='freights_lo_trackin_cacbc5_idx'),
        ),
        migrations.AddIndex(
            model_name='locationpoint',
            index=models.Index(fields=['organization', 'recorded_at'], name='freights_lo_organiz_c28fae_idx'),
        ),
        migrations.AddConstraint(
            model_name='locationpoint',
            constraint=models.UniqueConstraint(condition=models.Q(('client_event_id__isnull', False)), fields=('tracking_session', 'client_event_id'), name='unique_location_point_client_event_id'),
        ),
        migrations.AddConstraint(
            model_name='locationpoint',
            constraint=models.UniqueConstraint(condition=models.Q(('sequence__isnull', False)), fields=('tracking_session', 'sequence'), name='unique_location_point_sequence'),
        ),
    ]
