# Generated by Django 5.2.17 on 2026-08-16 17:15

import django.db.models.deletion
import src.freights.domain.enums
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carriers', '0003_carrierdocument'),
        ('drivers', '0004_driver_route_intent'),
        ('freights', '0007_trackingsession_locationpoint_and_more'),
        ('organizations', '0001_initial'),
        ('vehicles', '0003_rename_verified_at_vehicledocument_reviewed_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThermalReading',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_id', models.CharField(max_length=100)),
                ('sensor_timestamp', models.DateTimeField()),
                ('server_timestamp', models.DateTimeField(auto_now_add=True)),
                ('temperature_c', models.DecimalField(decimal_places=2, max_digits=6)),
                ('is_valid', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['sensor_timestamp'],
            },
        ),
        migrations.AddField(
            model_name='freightoperation',
            name='delay_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='freightoperation',
            name='eta',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='freightoperation',
            name='load_type',
            field=models.CharField(blank=True, choices=[('FTL', 'FTL'), ('LTL', 'LTL')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='freightrequest',
            name='priority',
            field=models.CharField(choices=[('NORMAL', 'NORMAL'), ('URGENT', 'URGENT')], default=src.freights.domain.enums.FreightRequestPriority['NORMAL'], max_length=20),
        ),
        migrations.AddIndex(
            model_name='freightoperation',
            index=models.Index(fields=['organization', 'load_type'], name='freights_fr_organiz_0061e7_idx'),
        ),
        migrations.AddField(
            model_name='thermalreading',
            name='operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='thermal_readings', to='freights.freightoperation'),
        ),
        migrations.AddField(
            model_name='thermalreading',
            name='tracking_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thermal_readings', to='freights.trackingsession'),
        ),
        migrations.AddIndex(
            model_name='thermalreading',
            index=models.Index(fields=['operation', 'sensor_timestamp'], name='freights_th_operati_09ace3_idx'),
        ),
        migrations.AddIndex(
            model_name='thermalreading',
            index=models.Index(fields=['device_id', 'sensor_timestamp'], name='freights_th_device__8035ee_idx'),
        ),
        migrations.AddConstraint(
            model_name='thermalreading',
            constraint=models.UniqueConstraint(fields=('operation', 'device_id', 'sensor_timestamp'), name='unique_thermal_reading_per_op_device_ts'),
        ),
    ]
