# Generated by Django 5.2.17 on 2026-08-16 17:59

import django.db.models.deletion
import src.freights.domain.enums
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freights', '0008_add_logistics_fields'),
        ('vehicles', '0003_rename_verified_at_vehicledocument_reviewed_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThermalExcursion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sensor_id', models.CharField(blank=True, max_length=100, null=True)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('RESOLVED', 'RESOLVED')], default=src.freights.domain.enums.ThermalExcursionStatus['ACTIVE'], max_length=20)),
                ('direction', models.CharField(choices=[('BELOW_MIN', 'BELOW_MIN'), ('ABOVE_MAX', 'ABOVE_MAX')], max_length=20)),
                ('min_observed', models.DecimalField(decimal_places=2, max_digits=6)),
                ('max_observed', models.DecimalField(decimal_places=2, max_digits=6)),
                ('metadata', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='thermalreading',
            name='client_event_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='thermalreading',
            name='quality',
            field=models.CharField(choices=[('VALID', 'VALID'), ('INVALID', 'INVALID'), ('SUSPECT', 'SUSPECT'), ('STALE', 'STALE')], default=src.freights.domain.enums.ThermalReadingQuality['VALID'], max_length=20),
        ),
        migrations.AddField(
            model_name='thermalreading',
            name='validity',
            field=models.CharField(choices=[('VALID', 'VALID'), ('INVALID', 'INVALID'), ('SUSPECT', 'SUSPECT'), ('STALE', 'STALE')], default=src.freights.domain.enums.ThermalReadingValidity['VALID'], max_length=20),
        ),
        migrations.AddField(
            model_name='thermalreading',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thermal_readings', to='vehicles.vehicle'),
        ),
        migrations.AddIndex(
            model_name='thermalreading',
            index=models.Index(fields=['operation', 'client_event_id'], name='freights_th_operati_567a47_idx'),
        ),
        migrations.AddConstraint(
            model_name='thermalreading',
            constraint=models.UniqueConstraint(condition=models.Q(('client_event_id__isnull', True), _negated=True), fields=('operation', 'client_event_id'), name='unique_thermal_reading_client_event_id'),
        ),
        migrations.AddField(
            model_name='thermalexcursion',
            name='operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='thermal_excursions', to='freights.freightoperation'),
        ),
        migrations.AddIndex(
            model_name='thermalexcursion',
            index=models.Index(fields=['operation', 'status'], name='freights_th_operati_871cb7_idx'),
        ),
        migrations.AddIndex(
            model_name='thermalexcursion',
            index=models.Index(fields=['sensor_id', 'status'], name='freights_th_sensor__4bd636_idx'),
        ),
    ]
