# Generated by Django 5.2.17 on 2026-08-22 14:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freights', '0009_thermalexcursion_thermalreading_client_event_id_and_more'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proofofdelivery',
            name='operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pods', to='freights.freightoperation'),
        ),
        migrations.CreateModel(
            name='FreightOperationStop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.PositiveSmallIntegerField(default=1)),
                ('stop_type', models.CharField(choices=[('PICKUP', 'PICKUP'), ('DELIVERY', 'DELIVERY')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('ARRIVED', 'ARRIVED'), ('COMPLETED', 'COMPLETED'), ('CANCELLED', 'CANCELLED')], default='PENDING', max_length=30)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('street', models.CharField(blank=True, max_length=180)),
                ('number', models.CharField(blank=True, max_length=20)),
                ('complement', models.CharField(blank=True, max_length=180)),
                ('district', models.CharField(blank=True, max_length=80)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('state', models.CharField(blank=True, max_length=2)),
                ('country', models.CharField(blank=True, default='BR', max_length=2)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('instructions', models.TextField(blank=True)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='freights.freightoperation')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='freight_operation_stops', to='organizations.organization')),
                ('request_stop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operation_stops', to='freights.freightrequeststop')),
            ],
            options={
                'ordering': ['sequence', 'stop_type'],
            },
        ),
        migrations.CreateModel(
            name='FreightOperationCargoLot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=255)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('volume_m3', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('package_count', models.PositiveIntegerField(blank=True, null=True)),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargo_lots', to='freights.freightoperation')),
                ('delivery_stop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_cargo_lots', to='freights.freightoperationstop')),
                ('pickup_stop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pickup_cargo_lots', to='freights.freightoperationstop')),
            ],
        ),
        migrations.AddField(
            model_name='proofofdelivery',
            name='stop',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stop_pod', to='freights.freightoperationstop'),
        ),
        migrations.CreateModel(
            name='FreightCargoLot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=255)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('volume_m3', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('package_count', models.PositiveIntegerField(blank=True, null=True)),
                ('delivery_stop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_cargo_lots', to='freights.freightrequeststop')),
                ('freight_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargo_lots', to='freights.freightrequest')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='freight_cargo_lots', to='organizations.organization')),
                ('pickup_stop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pickup_cargo_lots', to='freights.freightrequeststop')),
            ],
            options={
                'indexes': [models.Index(fields=['freight_request'], name='freights_fr_freight_2b6ff9_idx'), models.Index(fields=['pickup_stop'], name='freights_fr_pickup__506b9c_idx'), models.Index(fields=['delivery_stop'], name='freights_fr_deliver_85d3f8_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='freightoperationstop',
            index=models.Index(fields=['operation', 'status'], name='freights_fr_operati_b27a61_idx'),
        ),
        migrations.AddIndex(
            model_name='freightoperationstop',
            index=models.Index(fields=['operation', 'sequence'], name='freights_fr_operati_2735fd_idx'),
        ),
        migrations.AddConstraint(
            model_name='freightoperationstop',
            constraint=models.UniqueConstraint(fields=('operation', 'sequence'), name='unique_freight_operation_stop_sequence'),
        ),
        migrations.AddIndex(
            model_name='freightoperationcargolot',
            index=models.Index(fields=['operation'], name='freights_fr_operati_f45ce9_idx'),
        ),
        migrations.AddIndex(
            model_name='freightoperationcargolot',
            index=models.Index(fields=['pickup_stop'], name='freights_fr_pickup__7b2cef_idx'),
        ),
        migrations.AddIndex(
            model_name='freightoperationcargolot',
            index=models.Index(fields=['delivery_stop'], name='freights_fr_deliver_569d93_idx'),
        ),
    ]
