# Generated by Django 5.2.17 on 2026-08-22 15:37

import django.db.models.deletion
import src.freights.domain.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carriers', '0003_carrierdocument'),
        ('drivers', '0005_driverpreference_driverregionpreference'),
        ('freights', '0010_alter_proofofdelivery_operation_freightoperationstop_and_more'),
        ('organizations', '0001_initial'),
        ('vehicles', '0003_rename_verified_at_vehicledocument_reviewed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='freightoperation',
            name='source_type',
            field=models.CharField(choices=[('MARKETPLACE', 'MARKETPLACE'), ('CONTRACTED_ROUTE', 'CONTRACTED_ROUTE'), ('MANUAL', 'MANUAL'), ('API', 'API')], default=src.freights.domain.enums.OperationSource['MARKETPLACE'], max_length=30),
        ),
        migrations.AlterField(
            model_name='freightoperation',
            name='selection',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operation', to='freights.freightofferselection'),
        ),
        migrations.AddConstraint(
            model_name='freightoperation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('selection__isnull', False), ('source_type', 'MARKETPLACE')), models.Q(('source_type', 'MARKETPLACE'), _negated=True), _connector='OR'), name='chk_marketplace_operation_has_selection'),
        ),
    ]
