# Generated by Django 5.2.17 on 2026-08-22 19:20

import django.db.models.deletion
import src.freights.domain.enums
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carriers', '0003_carrierdocument'),
        ('customers', '0002_seed_customer_permissions'),
        ('drivers', '0005_driverpreference_driverregionpreference'),
        ('freights', '0011_freightoperation_source_type_and_more'),
        ('organizations', '0001_initial'),
        ('vehicles', '0003_rename_verified_at_vehicledocument_reviewed_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractedRoute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('DRAFT', 'DRAFT'), ('ACTIVE', 'ACTIVE'), ('PAUSED', 'PAUSED'), ('EXPIRED', 'EXPIRED'), ('CANCELLED', 'CANCELLED')], default=src.freights.domain.enums.ContractedRouteStatus['DRAFT'], max_length=30)),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField()),
                ('load_type', models.CharField(choices=[('FTL', 'FTL'), ('LTL', 'LTL')], max_length=3)),
                ('sla', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContractedRouteOccurrence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('occurrence_date', models.DateField()),
                ('status', models.CharField(choices=[('PLANNED', 'PLANNED'), ('MATERIALIZED', 'MATERIALIZED'), ('CANCELLED', 'CANCELLED')], default=src.freights.domain.enums.ContractedRouteOccurrenceStatus['PLANNED'], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ContractedRouteStop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.PositiveSmallIntegerField()),
                ('stop_type', models.CharField(choices=[('PICKUP', 'PICKUP'), ('DELIVERY', 'DELIVERY')], max_length=20)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('street', models.CharField(blank=True, max_length=180)),
                ('number', models.CharField(blank=True, max_length=20)),
                ('complement', models.CharField(blank=True, max_length=180)),
                ('district', models.CharField(blank=True, max_length=80)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('state', models.CharField(blank=True, max_length=2)),
                ('country', models.CharField(blank=True, default='BR', max_length=2)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('instructions', models.TextField(blank=True)),
                ('window_start', models.TimeField(blank=True, null=True)),
                ('window_end', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContractedRouteWeekday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('MON', 'MON'), ('TUE', 'TUE'), ('WED', 'WED'), ('THU', 'THU'), ('FRI', 'FRI'), ('SAT', 'SAT'), ('SUN', 'SUN')], max_length=3)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='freightoperation',
            name='chk_marketplace_operation_has_selection',
        ),
        migrations.AddConstraint(
            model_name='freightoperation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('selection__isnull', False), ('source_type', 'MARKETPLACE')), models.Q(models.Q(('source_type', 'MARKETPLACE'), _negated=True), ('selection__isnull', True)), _connector='OR'), name='chk_operation_source_selection_match'),
        ),
        migrations.AddField(
            model_name='contractedroute',
            name='carrier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracted_routes', to='carriers.carrierprofile'),
        ),
        migrations.AddField(
            model_name='contractedroute',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracted_routes', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='contractedroute',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracted_routes', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='contractedroute',
            name='preferred_driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contracted_routes', to='drivers.driver'),
        ),
        migrations.AddField(
            model_name='contractedroute',
            name='preferred_vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contracted_routes', to='vehicles.vehicle'),
        ),
        migrations.AddField(
            model_name='contractedrouteoccurrence',
            name='contracted_route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='occurrences', to='freights.contractedroute'),
        ),
        migrations.AddField(
            model_name='contractedrouteoccurrence',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='occurrences', to='drivers.driver'),
        ),
        migrations.AddField(
            model_name='contractedrouteoccurrence',
            name='operation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occurrence', to='freights.freightoperation'),
        ),
        migrations.AddField(
            model_name='contractedrouteoccurrence',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracted_route_occurrences', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='contractedrouteoccurrence',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='occurrences', to='vehicles.vehicle'),
        ),
        migrations.AddField(
            model_name='contractedroutestop',
            name='contracted_route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='freights.contractedroute'),
        ),
        migrations.AddField(
            model_name='contractedroutestop',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracted_route_stops', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='contractedrouteweekday',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekdays', to='freights.contractedroute'),
        ),
        migrations.AddConstraint(
            model_name='contractedroute',
            constraint=models.CheckConstraint(condition=models.Q(('valid_until__gte', models.F('valid_from'))), name='chk_contracted_route_valid_dates'),
        ),
        migrations.AddConstraint(
            model_name='contractedrouteoccurrence',
            constraint=models.UniqueConstraint(fields=('contracted_route', 'occurrence_date'), name='unique_contracted_route_occurrence_date'),
        ),
        migrations.AddConstraint(
            model_name='contractedroutestop',
            constraint=models.UniqueConstraint(fields=('contracted_route', 'sequence'), name='unique_contracted_route_stop_sequence'),
        ),
        migrations.AddConstraint(
            model_name='contractedrouteweekday',
            constraint=models.UniqueConstraint(fields=('route', 'day'), name='unique_contracted_route_weekday'),
        ),
    ]
