# Generated by Django 5.2.17 on 2026-08-22 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freights', '0012_contractedroute_contractedrouteoccurrence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='freightoperationstop',
            name='window_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='freightoperationstop',
            name='window_start',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
