# Generated by Django 5.2.17 on 2026-08-23 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freights', '0013_freightoperationstop_window_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractedroute',
            name='temperature_max_c',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Temperatura máxima exigida da carga na rota.', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='contractedroute',
            name='temperature_min_c',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Temperatura mínima exigida da carga na rota.', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='freightoperation',
            name='temperature_max_c',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Snapshot da temperatura máxima permitida da carga.', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='freightoperation',
            name='temperature_min_c',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Snapshot da temperatura mínima permitida da carga.', max_digits=5, null=True),
        ),
    ]
